### ISSUE TITLE
Incorrect parsing of boolean values ("0" and "1" are rejected)

### ISSUE THREAD

**Issue by rhuitl** [networkx/networkx#1385]
The following GraphML document created by boost::write_graphml() fails to parse because of the "0" value in a boolean attribute:

````xml
<?xml version="1.0" encoding="UTF-8"?>
<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
  <key id="key0" for="edge" attr.name="stairs" attr.type="boolean" />
  <key id="key1" for="node" attr.name="x" attr.type="float" />
  <key id="key2" for="node" attr.name="y" attr.type="float" />
  <key id="key3" for="node" attr.name="z" attr.type="float" />
  <graph id="G" edgedefault="undirected" parse.nodeids="canonical" parse.edgeids="canonical" parse.order="nodesfirst">
    <node id="n0">
      <data key="key1">-8.65329</data>
      <data key="key2">-56.0669</data>
      <data key="key3">0.0036082</data>
    </node>
    <node id="n1">
      <data key="key1">-7.78193</data>
      <data key="key2">-55.916</data>
      <data key="key3">0.000559049</data>
    </node>
    <edge id="e0" source="n0" target="n1">
      <data key="key0">0</data>
    </edge>
  </graph>
</graphml>
````

````
>>> networkx.read_graphml("/tmp/bool.graphml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 2, in read_graphml
  File "/usr/lib/python2.7/dist-packages/networkx/utils/decorators.py", line 263, in _open_file
    result = func(*new_args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/networkx/readwrite/graphml.py", line 153, in read_graphml
    glist=list(reader(path=path))
  File "/usr/lib/python2.7/dist-packages/networkx/readwrite/graphml.py", line 404, in __call__
    yield self.make_graph(g, keys, defaults)
  File "/usr/lib/python2.7/dist-packages/networkx/readwrite/graphml.py", line 433, in make_graph
    self.add_edge(G, edge_xml, graphml_keys)
  File "/usr/lib/python2.7/dist-packages/networkx/readwrite/graphml.py", line 479, in add_edge
    data = self.decode_data_elements(graphml_keys, edge_element)
  File "/usr/lib/python2.7/dist-packages/networkx/readwrite/graphml.py", line 508, in decode_data_elements
    data[data_name] = self.convert_bool[text]
KeyError: '0'
````
According to http://www.w3.org/TR/xmlschema-2/#boolean, acceptable values for true are "true" and "1", for false it is "false" and "0".

**Comment by hagberg** [comment]
The GraphML spec says http://graphml.graphdrawing.org/primer/graphml-primer.html#AttributesDefinition
The type of the GraphML-Attribute can be either boolean, int, long, float, double, or string. These types are defined like the corresponding types in the Java(TM)-Programming language.

I'm not a Java(TM) Programmer so someone might chime in with info on booleans.  At any rate I don't see why we shouldn't accept 1 and 0 as booleans in this case.

**Comment by rhuitl** [comment]
Actually it seems to be fixed already in the latest version, but that hasn't made it into Ubuntu 14.04 repositories yet :(
