### ISSUE TITLE
write_gml can't deal with unicode nodes

### ISSUE THREAD

**Issue by joernhees** [networkx/networkx#1400]
```python
>>> import networkx as nx
>>> g = nx.Graph()
>>> g.add_edge(u'jörn', u'hees')
>>> nx.write_gml(g, 'test.gml')
Traceback (most recent call last):
  File "<ipython-input-8-6fb929548fcc>", line 1, in <module>
    nx.write_gml(g, 'test.gml')
  File "<string>", line 2, in write_gml
  File "/usr/local/lib/python2.7/site-packages/networkx/utils/decorators.py", line 220, in _open_file
    result = func(*new_args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/networkx/readwrite/gml.py", line 429, in write_gml
    for line in generate_gml(G):
  File "/usr/local/lib/python2.7/site-packages/networkx/readwrite/gml.py", line 364, in generate_gml
    label = str(G.node[n].get('label',n))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 1: ordinal not in range(128)
```

**Comment by ysitu** [comment]
This has been fixed, but the fix has not yet been released.

**Comment by hagberg** [comment]
GML is 7-bit ASCII format.  So it isn't an appropriate format to store non-ASCII characters.
https://www.fim.uni-passau.de/fileadmin/files/lehrstuhl/brandenburg/projekte/gml/gml-technical-report.pdf

**Comment by joernhees** [comment]
hmm ok, thanks...
