### ISSUE TITLE
node name not shown

### ISSUE THREAD

**Issue by yw652** [networkx/networkx#1468]
I tried to create a some nodes for graphing and I want their names shown in the graph (such as 'A','B','C', etc). However, I wrote G.add_nodes_from(['A','B', 'C', 'D', 'E', 'F']), and all the nodes in the graph are just red spots with no indication of which is which. 

Is there something else I need to specify when I'm creating the nodes?

Many thanks!

**Comment by jg-you** [comment]
See [this example from the documentation](https://networkx.github.io/documentation/latest/examples/drawing/weighted_graph.html).
You need to add a call to [`draw_networkx_labels`](https://networkx.github.io/documentation/latest/reference/generated/networkx.drawing.nx_pylab.draw_networkx_labels.html?highlight=draw_networkx_labels).
```

**Comment by yw652** [comment]
@jg-you this is very weird. I copy the exact same code from the weighted graph example and ran it, the graph pops out but still not label appears. Below are the errors:

Traceback (most recent call last):
  File "/Users/yitongwang/anaconda/lib/python2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Users/yitongwang/anaconda/lib/python2.7/site-packages/matplotlib/figure.py", line 1079, in draw
    func(*args)
  File "/Users/yitongwang/anaconda/lib/python2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Users/yitongwang/anaconda/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2092, in draw
    a.draw(renderer)
  File "/Users/yitongwang/anaconda/lib/python2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Users/yitongwang/anaconda/lib/python2.7/site-packages/matplotlib/text.py", line 538, in draw
    bbox, info, descent = self._get_layout(renderer)
  File "/Users/yitongwang/anaconda/lib/python2.7/site-packages/matplotlib/text.py", line 311, in _get_layout
    ismath=False)
  File "/Users/yitongwang/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_macosx.py", line 166, in get_text_width_height_descent
    six.text_type(s), family, size, weight, style)
TypeError: bad argument type for built-in operation

Thanks!

**Comment by OrkoHunter** [comment]
@yw652 Yes that's weird. The exact same code works perfectly. However, Just so that you wanted the labelled nodes, this could be the simplest code. Try it?
```
import networkx as nx
import matplotlib.pyplot as plt

G = nx.Graph()

G.add_nodes_from(['A','B','C','D','E','F'])
pos = nx.spring_layout(G)

nx.draw_networkx_nodes(G,pos,node_size=700)
nx.draw_networkx_labels(G,pos,font_size=20,font_family='sans-serif')
plt.axis('off')
plt.show()
```

**Comment by yw652** [comment]
I figured out the problem: it's the version of matplotlib that's been messing around. I updated it to the newest version and it works now!

Many thanks @OrkoHunter @jg-you !
