### ISSUE TITLE
write_gexf does not handle Nones

### ISSUE THREAD

**Issue by Julian** [networkx/networkx#1490]
_Disclaimer: I know neither about XML nor GEXF, so apologies in advance_

```
from StringIO import StringIO
import networkx
s = StringIO()
g = networkx.Graph()
g.add_edge(1, 2, foo=None)
networkx.write_gexf(g, StringIO())
```

produces:

```
Traceback (most recent call last):
  File "<bpython-input-2>", line 2, in <module>
    from StringIO import StringIO; import networkx; s = StringIO(); g = networkx.Graph(); g.add_edge(1, 2, foo=None); networkx.write_gexf(g, StringIO())
  File "<string>", line 2, in write_gexf
  File "/usr/local/Cellar/pypy/2.5.1/libexec/site-packages/networkx/utils/decorators.py", line 220, in _open_file
    result = func(*new_args, **kwargs)
  File "/usr/local/Cellar/pypy/2.5.1/libexec/site-packages/networkx/readwrite/gexf.py", line 77, in write_gexf
    writer.add_graph(G)
  File "/usr/local/Cellar/pypy/2.5.1/libexec/site-packages/networkx/readwrite/gexf.py", line 300, in add_graph
    self.add_edges(G,graph_element)
  File "/usr/local/Cellar/pypy/2.5.1/libexec/site-packages/networkx/readwrite/gexf.py", line 391, in add_edges
    edge_data, default)
  File "/usr/local/Cellar/pypy/2.5.1/libexec/site-packages/networkx/readwrite/gexf.py", line 430, in add_attributes
    attr_id = self.get_attr_id(make_str(k), self.xml_type[val_type],
KeyError: <type 'NoneType'>
```

I'm not sure what the correct representation of `None` is in XML, but Google suggests there probably is at least one suitable one?

**Comment by chebee7i** [comment]
I'm not sure about this, but my inclination is not to "fix" this. There is no shortage of types that will not convert for the GEXF, tuples are among them as well. I saw this: http://stackoverflow.com/questions/774192/what-is-the-correct-way-to-represent-null-xml-elements, but it's not clear to me if that would even be a valid GEXF document.

**Comment by Julian** [comment]
*nods*, obviously I don't expect arbitrary serialization to work, especially if there isn't a canonical representation, but I'm not sure I see an existing API for actually specifying how to serialize and deserialize other types, which might be a nice thing if you don't actually decide to support all of the common Python data types at least.

**Comment by chebee7i** [comment]
Yeah, that's a good idea. Probably something similar to what we have for `write_gml`. https://github.com/networkx/networkx/pull/1269. Let's leave this open in case someone feels inspired.
