### ISSUE TITLE
read_graphml fails to open graphml file generated by Cytoscape

### ISSUE THREAD

**Issue by manihamidi** [networkx/networkx#2197]
networkx.read_graphml fails to import a graphml file generated by [Cytoscape](http://www.cytoscape.org/) returning the following error:

```
Traceback (most recent call last):

  File "<ipython-input-323-63e903596d6f>", line 1, in <module>
    G = nx.read_graphml(path_to_graphml_file)

  File "<decorator-gen-327>", line 2, in read_graphml

  File "C:\Users\Mani\Anaconda\lib\site-packages\networkx\utils\decorators.py", line 220, in _open_file
    result = func(*new_args, **kwargs)

  File "C:\Users\Mani\Anaconda\lib\site-packages\networkx\readwrite\graphml.py", line 154, in read_graphml
    return glist[0]
```

---
- Cytoscape is a popular graph visualization tool.

**Comment by manihamidi** [comment]
Temporary way of getting around the problem: 

Manually add these variables to the start-tag of the graphml file generated by cytoscape:
```
xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd"
```
i.e. open the graphml file in a text editor, and replace the second line (<graphml>) with this: 
```
 <graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
```

**Comment by ProgVal** [comment]
Can you provide an example file?

**Comment by manihamidi** [comment]
Here is the graphml file I generated and exported using Cytoscape 3.4.0: 

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<graphml>
    <key attr.name="SUID" attr.type="long" for="node" id="SUID"/>
    <key attr.name="shared name" attr.type="string" for="node" id="shared name"/>
    <key attr.name="name" attr.type="string" for="node" id="name"/>
    <key attr.name="selected" attr.type="boolean" for="node" id="selected"/>
    <key attr.name="first_attr" attr.type="int" for="node" id="first_attr"/>
    <key attr.name="second_attr" attr.type="string" for="node" id="second_attr"/>
    <key attr.name="SUID" attr.type="long" for="node" id="SUID"/>
    <key attr.name="shared name" attr.type="string" for="node" id="shared name"/>
    <key attr.name="shared interaction" attr.type="string" for="node" id="shared interaction"/>
    <key attr.name="name" attr.type="string" for="node" id="name"/>
    <key attr.name="selected" attr.type="boolean" for="node" id="selected"/>
    <key attr.name="interaction" attr.type="string" for="node" id="interaction"/>
    <key attr.name="SUID" attr.type="long" for="node" id="SUID"/>
    <key attr.name="shared name" attr.type="string" for="node" id="shared name"/>
    <key attr.name="name" attr.type="string" for="node" id="name"/>
    <key attr.name="selected" attr.type="boolean" for="node" id="selected"/>
    <key attr.name="__Annotations" attr.type="string" for="node" id="__Annotations"/>
    <graph edgedefault="directed" id="Network">
        <node id="63">
            <data key="SUID">63</data>
            <data key="shared name">Node 1</data>
            <data key="name">Node 1</data>
            <data key="selected">false</data>
            <data key="second_attr">'hello'</data>
        </node>
        <node id="62">
            <data key="SUID">62</data>
            <data key="shared name">Node 2</data>
            <data key="name">Node 2</data>
            <data key="selected">false</data>
            <data key="first_attr">1</data>
        </node>
        <edge source="63" target="62">
            <data key="SUID">64</data>
            <data key="shared name">Node 1 (interacts with) Node 2</data>
            <data key="shared interaction">interacts with</data>
            <data key="name">Node 1 (interacts with) Node 2</data>
            <data key="selected">false</data>
            <data key="interaction">interacts with</data>
        </edge>
    </graph>
</graphml>
```

and then I tried to open it with networkx and got this: 

```
G_t = nx.read_graphml(path_t)
Traceback (most recent call last):

  File "<ipython-input-21-4a0389e1bd47>", line 1, in <module>
    G_t = nx.read_graphml(path_t)

  File "<decorator-gen-328>", line 2, in read_graphml

  File "C:\Users\Mani\Anaconda\lib\site-packages\networkx\utils\decorators.py", line 220, in _open_file
    result = func(*new_args, **kwargs)

  File "C:\Users\Mani\Anaconda\lib\site-packages\networkx\readwrite\graphml.py", line 154, in read_graphml
    return glist[0]

IndexError: list index out of range

```
