### ISSUE TITLE
Random failures in test_agraph tests.

### ISSUE THREAD

**Issue by ProgVal** [networkx/networkx#2201]
Two tests in `test_agraph` sometimes fail on my machine.

After adding this code to `assert_equal`:

```
        print(sorted(G1.edges()))
        print(sorted(G2.edges()))
```

the errors are:

```
======================================================================
FAIL: test_agraph.TestAGraph.testMultiUndirected
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/progval/.local/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/progval/dev/networkx/networkx/drawing/tests/test_agraph.py", line 63, in testMultiUndirected
    self.agraph_checks(nx.MultiGraph())
  File "/home/progval/dev/networkx/networkx/drawing/tests/test_agraph.py", line 33, in agraph_checks
    self.assert_equal(G, H)
  File "/home/progval/dev/networkx/networkx/drawing/tests/test_agraph.py", line 27, in assert_equal
    assert_true( sorted(G1.edges()) == sorted(G2.edges()) )
nose.proxy.AssertionError: False is not true
-------------------- >> begin captured stdout << ---------------------
[('B', 'A'), ('B', 'C'), ('C', 'A'), ('C', 'A'), ('D', 'A')]
[('A', 'C'), ('A', 'C'), ('B', 'A'), ('B', 'C'), ('D', 'A')]

--------------------- >> end captured stdout << ----------------------
    'False is not true' = self._formatMessage('False is not true', "%s is not true" % safe_repr(False))
>>  raise self.failureException('False is not true')


======================================================================
FAIL: test_agraph.TestAGraph.testUndirected
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/progval/.local/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/progval/dev/networkx/networkx/drawing/tests/test_agraph.py", line 57, in testUndirected
    self.agraph_checks(nx.Graph())
  File "/home/progval/dev/networkx/networkx/drawing/tests/test_agraph.py", line 33, in agraph_checks
    self.assert_equal(G, H)
  File "/home/progval/dev/networkx/networkx/drawing/tests/test_agraph.py", line 27, in assert_equal
    assert_true( sorted(G1.edges()) == sorted(G2.edges()) )
nose.proxy.AssertionError: False is not true
-------------------- >> begin captured stdout << ---------------------
[('B', 'A'), ('B', 'C'), ('C', 'A'), ('D', 'A')]
[('A', 'C'), ('B', 'A'), ('B', 'C'), ('D', 'A')]

--------------------- >> end captured stdout << ----------------------
    'False is not true' = self._formatMessage('False is not true', "%s is not true" % safe_repr(False))
>>  raise self.failureException('False is not true')


----------------------------------------------------------------------
```

Using networkx from the `master` branch.

**Comment by hagberg** [comment]
It looks like we should be using `networkx.testing.utils.assert_edges_equal()` here.

**Comment by hagberg** [comment]
See #2203 and friends.
