### ISSUE TITLE
memory error when  run current_flow_betweenness_centrality & edge_current_flow_betweenness_centrality

### ISSUE THREAD

**Issue by Laguna-Liu** [networkx/networkx#2300]
Hi all,
I run the code on my PC(windows 7 x64, 8g RAM), and I met memory error when run current_flow_betweenness_centrality & edge_current_flow_betweenness_centrality.

The message as following:
Traceback (most recent call last):
  File "C:/Users/xuehui/Desktop/connected input.py", line 40, in <module>
    p.dump(nx.current_flow_betweenness_centrality(H),file8)
  File "D:\python\lib\site-packages\networkx-1.11-py2.7.egg\networkx\algorithms\centrality\current_flow_betweenness.py", line 233, in current_flow_betweenness_centrality
    solver=solver):
  File "D:\python\lib\site-packages\networkx-1.11-py2.7.egg\networkx\algorithms\centrality\flow_matrix.py", line 16, in flow_matrix_row
    C = solvername[solver](L, dtype=dtype) # initialize solver
  File "D:\python\lib\site-packages\networkx-1.11-py2.7.egg\networkx\algorithms\centrality\flow_matrix.py", line 46, in __init__
    self.init_solver(L)
  File "D:\python\lib\site-packages\networkx-1.11-py2.7.egg\networkx\algorithms\centrality\flow_matrix.py", line 81, in init_solver
    self.IL = np.zeros(L.shape, dtype=self.dtype)
MemoryError

I thought the problem may come from my own code(H = list
(nx.connected_component_subgraphs(G))[0] 
p.dump(nx.current_flow_closeness_centrality(H),file8))

G is a graph with 40000 nodes and 200000 edges.

What should I do to solve this problem?
Thanks!

**Comment by suntxy** [comment]
I am having same issue in a graph with 20000 nodes and 1000000 edges,  probably make sure you are using python2.7 64, it will allow you to use more memory than 32 bit python.

**Comment by hagberg** [comment]
It looks like it is using al of your memory.  The most likely solutions are to find a more efficient memory implementation or a machine with more memory.  Unfortunately the current flow centrality algorithms require a linear equation solve which uses a lot of memory.   You might also try the "cg" solver option to current_flow_betweenness_centrality which uses less memory.
