### ISSUE TITLE
find_cycle() doesn't find cycle in cyclic digraph

### ISSUE THREAD

**Issue by joebockhorst** [networkx/networkx#2323]
```python
print("version: {}".format(nx.__version__))
dg = nx.DiGraph()
dg.add_edge(1, 0)
dg.add_edge(2, 0)
dg.add_edge(1, 2)
dg.add_edge(2, 1)
find_cycle(dg)
```

```
version: 1.11
Traceback (most recent call last):

  File "<ipython-input-127-ea87764febbd>", line 7, in <module>
    find_cycle(dg)

  File "xxxx\AppData\Local\Continuum\Anaconda\lib\site-packages\networkx\algorithms\cycles.py", line 453, in find_cycle
    raise nx.exception.NetworkXNoCycle('No cycle found.')
```

I believe the problem lies in that when `head` is a previously explored node all paths from the current `start_node` are ignored instead of just pruning from `head`

```python
elif head in explored:
     # Then we've already explored it. No loop is possible.
     break
```

Removing this condition fixes the bug as far as I can tell given the graphs I am working with. However, a more efficient solution that does proper pruning would be more efficient especially for larger graphs.

**Comment by chebee7i** [comment]
Thanks for the report @joebockhorst!

**Comment by mkazemb** [comment]
Hello,
I have a similar problem.
```
G=nx.MultiDiGraph()
G.add_edge('b','a')
G.add_edge('b','a')
nx.find_cycles(G)
```
Even with the updated code:
```
Traceback (most recent call last):
  File "xxxx\AppData\Local\Continuum\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-566f906fa8d3>", line 1, in <module>
    nx.find_cycle(G)
  File "xxxx\AppData\Local\Continuum\Anaconda3\lib\site-packages\networkx\algorithms\cycles.py", line 423, in find_cycle
    raise nx.exception.NetworkXNoCycle('No cycle found.')
networkx.exception.NetworkXNoCycle: No cycle found.
```
I am using version 1.11
