### ISSUE TITLE
read_edgelist doesn't read the output of write_edgelist for data values with line breaks

### ISSUE THREAD

**Issue by yucer** [networkx/networkx#2584]
This is a simple python script reproducing the error (`nx_issue_edge_with_breaks.py `): 

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import networkx as nx

G = nx.MultiDiGraph()
G.add_edge(1, 3, description="Sample edge 1 \n with line break")

G = nx.write_edgelist(G, 'temp.csv', data=True)

G2 = nx.MultiDiGraph()
G2 = nx.read_edgelist('temp.csv', create_using=G2, data=True)
```

note that the generated `.csv` has actually two lines:

```bash
$ cat temp.csv 
1 3 {'description': 'Sample edge 1 
 with line break'}
```

and the error during the read is:

```bash
$ ./nx_issue_edge_with_breaks.py 
Traceback (most recent call last):
  File "./nx_issue_edge_with_breaks.py", line 12, in <module>
    G2 = nx.read_edgelist('temp.csv', create_using=G2, data=True)
  File "<decorator-gen-170>", line 2, in read_edgelist
  File "/home/yucer/.virtualenvs/odoorpc/local/lib/python2.7/site-packages/networkx/utils/decorators.py", line 220, in _open_file
    result = func(*new_args, **kwargs)
  File "/home/yucer/.virtualenvs/odoorpc/local/lib/python2.7/site-packages/networkx/readwrite/edgelist.py", line 369, in read_edgelist
    data=data)
  File "/home/yucer/.virtualenvs/odoorpc/local/lib/python2.7/site-packages/networkx/readwrite/edgelist.py", line 280, in parse_edgelist
    "Failed to convert edge data (%s) to dictionary."%(d))
TypeError: Failed to convert edge data ([u"{'description':", u"'Sample", u'edge', u'1']) to dictionary.

```

and it confuses the reader. Can something be done transparently in this case without having to reprocess all the edges of the graph ?

**Comment by ProgVal** [comment]
Could be solved using `repr()` for writing and `ast.literal_eval()` for reading.

**Comment by hagberg** [comment]
This works correctly with Python3.  A Python2 workaround is to use a raw string, e.g.
```python
G.add_edge(1, 3, description=r"Sample edge 1 \n with line break")
```
