### ISSUE TITLE
Exception on missing  dist-info RECORD file, v 2.0

### ISSUE THREAD

**Issue by aramgrigoryan** [networkx/networkx#2692]
hi, this happens during uninstalling or installing other packages that require networkx
```
Exception:
Traceback (most recent call last):
  File "/home/agrigoryan/python3/usr/local/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/agrigoryan/python3/usr/local/lib/python3.6/site-packages/pip/commands/uninstall.py", line 76, in run
    requirement_set.uninstall(auto_confirm=options.yes)
  File "/home/agrigoryan/python3/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 346, in uninstall
    req.uninstall(auto_confirm=auto_confirm)
  File "/home/agrigoryan/python3/usr/local/lib/python3.6/site-packages/pip/req/req_install.py", line 694, in uninstall
    for path in pip.wheel.uninstallation_paths(dist):
  File "/home/agrigoryan/python3/usr/local/lib/python3.6/site-packages/pip/wheel.py", line 534, in unique
    for item in fn(*args, **kw):
  File "/home/agrigoryan/python3/usr/local/lib/python3.6/site-packages/pip/wheel.py", line 553, in uninstallation_paths
    r = csv.reader(FakeFile(dist.get_metadata_lines('RECORD')))
  File "/home/agrigoryan/python3/usr/local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1472, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/home/agrigoryan/python3/usr/local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1468, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "/home/agrigoryan/python3/usr/local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1577, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/home/agrigoryan/virtenv/lib/python3.6/site-packages/networkx-2.0.dist-info/RECORD'
```

**Comment by dschult** [comment]
To be able to help we need much more/better information... but first you need to narrow down what's going on, follow up on the error messages to see if files exist etc.
