### ISSUE TITLE
 remove_edges_from causing RuntimeError on certain view generators

### ISSUE THREAD

**Issue by ahrenberg** [networkx/networkx#2717]
In certain cases when remove_edges_from is operating on an view generator it will fail with a RuntimeError due to the yielded objects being the same as those removed.

I have observed it in two cases:

1. On on view returned by nx.selfloop_edges operating on MultiGraph and MultiDiGraph objects.  `G.remove_edges_from(nx.selfloop_edges(G))` is a standard construction for removing self-loops. It works with Graph and DiGraph, but fails for MultiGraph and MultiDiGraph.

2. On the view returned by nx.edges for all graph types. The construction `G.remove_edges_from(nx.edges(G))` might not be very useful, but the error also occurs when using functions from itertools to manipulate the view of nx.edges(G). Examples below.

Of course, in 2 the behaviour might perhaps be expected - the view seems to be an iterator to the same object as being manipulated, which is problematic. (A workaround is of course to create a list from it.) 

However in 1, the selfloop view seems to be handled for Graph and DiGraph, so might it not be expected to work also for the ones provided for MultiGraph and MultiDiGraph?

## Error-producing example
These three examples all fail:

### Removing self-loops from MultiGraph
```
import networkx as nx
G = nx.MultiGraph([(0,0), (1,1), (0,1)])
G.remove_edges_from(nx.selfloop_edges(G)) # Fail here
```
#### Error Message
```
Traceback (most recent call last):                                                                                    
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/networkx/classes/multigraph.py", line 603, in remove_edges_from              
    for e in ebunch:                                                                                                  
  File "/usr/lib/python3.6/site-packages/networkx/classes/function.py", line 1150, in <genexpr>
    if n in nbrs for d in nbrs[n].values())
  File "/usr/lib/python3.6/_collections_abc.py", line 761, in __iter__
    for key in self._mapping:
RuntimeError: dictionary changed size during iteration
```

### Removing all edges from Graph
```
import networkx as nx
G = nx.Graph([(0,1), (1,2), (2,3)])
G.remove_edges_from(nx.edges(G)) # Fail here
```
#### Error Message
```
Traceback (most recent call last):                                                                                    
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/networkx/classes/graph.py", line 1038, in remove_edges_from                  
    for e in ebunch:                                                                                                  
  File "/usr/lib/python3.6/site-packages/networkx/classes/reportviews.py", line 1024, in __iter__
    for nbr in nbrs:
RuntimeError: dictionary changed size during iteration
```

### Manipulating edge view using itertools:
```
import networkx as nx
import itertools
G = nx.DiGraph([(0,1), (1,2), (2,3)])
# Remove edges not staring at 1.
e_iter = itertools.filterfalse(lambda e : e[0] == 1, nx.edges(G))
G.remove_edges_from(e_iter) # Fail here
```
#### Error Message
```
Traceback (most recent call last):                                                                                    
  File "<stdin>", line 1, in <module>                                                                                 
  File "/usr/lib/python3.6/site-packages/networkx/classes/digraph.py", line 753, in remove_edges_from                 
    for e in ebunch:                                                                                                  
  File "/usr/lib/python3.6/site-packages/networkx/classes/reportviews.py", line 914, in __iter__
    for nbr in nbrs:
RuntimeError: dictionary changed size during iteration
```

## Version information
NetworkX: 2.0 
sys.version_info(major=3, minor=6, micro=2, releaselevel='final', serial=0)

Finally, thanks for your work on NetworkX.

**Comment by dschult** [comment]
Thanks for the Issue and for your careful writeup with good examples.

This looks like the same behavior that occurs for dicts.

    d = {n: n for n in range(4)}
    for n in d:
        del d[n]
    RuntimeError: dictionary changed size during iteration

It happens when iterating over ```d``` and over ```d.keys()```, etc. Basically, any time you iterate over a dict, you can't change the dict. As you mention, you can/should use ```list(d)``` or similar to make sure not to change a dict you are iterating over. 

I don't think we can make that work without failure unless we 1) don't use iterators/views or 2) don't use dicts.

That said, I don't quite understand why the Graph and DiGraph methods are OK with deleting selfloops. It looks like the inner dict of our data structure does not get iterated over so the changing size of that dict doesn't interfere with the iteration. I would claim the lack of failure for Graph and DiGraph is a lucky happenstance. It is still changing a data structure involving hashes while iterating over that structure.  So.....

What do you think of the following?
We add documentation to remind people that when iterating over a NetworkX Graph while removing nodes and edges, you should use e.g. ```list(G.selfloop_edges())``` or ```list(G.edges)``` just as you would when changing a dict while iterating.

**Comment by ahrenberg** [comment]
Thanks for your reply!

I agree, it's the same problem as with dicts, and one can not expect it to work in that case. I mistakenly thought it had been explitly handled in Graph/DiGraph, but if them working is a luckly happenstance, as you write, I would not expect it for their Multi-counterparts either. 

The most straight forward way of addressing this is, as you say, probably by documenting it.

I would however argue that the documentation should be updated to warn people from providing View generators as a "bunch" parameter to _any_ function operating on the same graph as providing the View, not only to `remove_edges`. 

When thinking about your reply I realized that the following would also fail:

```
import networkx as nx
G = nx.Graph([(1,2),(2,3),(3,4)])
# Grow graph by one new node, adding edges to all existing.
G.add_edges_from(((5,n) for n in G.nodes))
```
At least to me such a construction seems plausible when generating a network, and might tempting to programmers. Again, simply changing to list comprehension here will fix the issue.

As for remove_edges, I can think of two docstrings which might need updating: `configuration_model` and `directed_configuration_model`. These include examples for getting rid of selfloops using the `G.remove_edges(nx.selfloop_edges(G))` construction. These examples work as they stand right now, because the MultiGraph is converted to a Graph (G) before the selfloop edges are removed. However, if the user wants to keep the MultiGraph object while removing the selfoops they'll fail.

Hope this helps, and let me know if I can be of assistance.

**Comment by SultanOrazbayev** [comment]
> As for remove_edges, I can think of two docstrings which might need updating: configuration_model and directed_configuration_model. These include examples for getting rid of selfloops using the G.remove_edges(nx.selfloop_edges(G)) construction. These examples work as they stand right now, because the MultiGraph is converted to a Graph (G) before the selfloop edges are removed. However, if the user wants to keep the MultiGraph object while removing the selfoops they'll fail.

Interestingly, keeping the object as `MultiGraph` or `MultiDiGraph` does not change the status of the code, it still works for removing selfloops. Hence, the docstrings for `configuration_model` and `directed_configuration_model` were not altered.
