### ISSUE TITLE
TypeError: iter() returned non-iterator of type 'Layer'

### ISSUE THREAD

**Issue by Asterrea** [networkx/networkx#2719]
I'm running NetworkX in a virtualenv using Python 3.5. With the same shapefiles, my python 2.7 instance can process them, but my 3.5 cannot. It prevails with this error even after I made an upgrade:

`Traceback (most recent call last):
  File "/home/gridlockdev/Desktop/heroku/grace/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/gridlockdev/Desktop/heroku/grace/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/gridlockdev/Desktop/heroku/grace/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gridlockdev/Desktop/heroku/grace/network/views.py", line 104, in geojson_to_shp
    render_network()
  File "/home/gridlockdev/Desktop/heroku/grace/network/views.py", line 112, in render_network
    G = nx.read_shp(directory, simplify=False)
  File "/home/gridlockdev/Desktop/heroku/grace/env/lib/python3.5/site-packages/networkx/readwrite/nx_shp.py", line 71, in read_shp
    for f in lyr:
TypeError: iter() returned non-iterator of type 'Layer'
`

>>> import pkg_resources
 >>> pkg_resources.get_distribution("networkx").version 
'1.11'`

**Comment by hagberg** [comment]
We'll need more details to find where this issue is.  A small example would be helpful.
