### ISSUE TITLE
How to use remove_edges_from() funtion with in_edges() funtion? 

### ISSUE THREAD

**Issue by beastsenior** [networkx/networkx#2761]
I am new to use networkx (networkx 2.0). I tried following codes: 
```
import matplotlib.pyplot as plt
import networkx as nx
Gstar = nx.star_graph(4)
Gstar = Gstar.to_directed()
a=Gstar.in_edges([0])
print(a)
Gstar.remove_edges_from(a)
# Gstar.remove_edges_from([(1, 0), (2, 0), (3, 0), (4, 0)])
# Gstar.remove_edges_from(eval(str(a)))
nx.draw(Gstar, with_labels=True)
plt.show()
```
got errors:
```
[(1, 0), (2, 0), (3, 0), (4, 0)]
Traceback (most recent call last):
  File "C:/GO/work/mycloud/360Cloud/program/networkx_test/2.py", line 8, in <module>
    Gstar.remove_edges_from(a)
  File "C:\Users\linger\AppData\Local\Programs\Python\Python36\lib\site-packages\networkx\classes\digraph.py", line 753, in remove_edges_from
    for e in ebunch:
  File "C:\Users\linger\AppData\Local\Programs\Python\Python36\lib\site-packages\networkx\classes\reportviews.py", line 736, in <genexpr>
    for nbr, dd in nbrs.items())
RuntimeError: dictionary changed size during iteration
```
but it will work by following codes:
`Gstar.remove_edges_from([(1, 0), (2, 0), (3, 0), (4, 0)])`
or
`Gstar.remove_edges_from(eval(str(a)))`
So how to use remove_edges_from() funtion with in_edges() funtion correctly? Thanks.

**Comment by beastsenior** [comment]
It works for me by using:
Gstar.remove_edges_from(tuple(a))
