### ISSUE TITLE
 topological_sort() got an unexpected keyword argument 'reverse'

### ISSUE THREAD

**Issue by bootrino** [networkx/networkx#2847]
I must be doing something obviously wrong here but I can't see it.

```
Traceback (most recent call last):
  File "call_tasks..py", line 87, in <module>
    get_dependency_sorted_node_list()
  File "call_tasks..py", line 76, in get_dependency_sorted_node_list
    for node_id in nx.topological_sort(G, reverse=True):
TypeError: topological_sort() got an unexpected keyword argument 'reverse'
(venv3.6) root@ubuntu-s-1vcpu-1gb-lon1-01:~#
```
Here's the code:
```
def get_dependency_sorted_node_list():
    for node_id in nx.topological_sort(G, reverse=True):
        print('VFX job id: {}'.format(node_id))
        print('VFX job dependencies: {}'.format(G[node_id]))
        node_attributes = G.node[node_id]
        print('VFX job state: {}'.format(node_attributes['state']))
        print('VFX job action: {}'.format(node_attributes['definition']['action']))
        print('VFX job arguments: {}'.format(node_attributes['definition']['arguments']))

```

**Comment by dschult** [comment]
The ```reverse``` keyword is not valid in v2.
With the new View classes, you should try ```nx.topological_sort(G.reverse())```

**Comment by bootrino** [comment]
Perhaps the docs could point this out... thanks for the reply.
