### ISSUE TITLE
is_connected is not implemented for directed graphs

### ISSUE THREAD

**Issue by boompig** [networkx/networkx#2858]
Python version: 3.6.0
nx version: 2.1

Simplest example:

```
import networkx as nx

vertices = [1, 2, 3, 4]
edges = [(1, 2), (1, 3), (1, 4)]

g = nx.DiGraph()
for edge in edges:
    g.add_edge(edge[0], edge[1])

print(nx.is_connected(g))
```

What should happen:

Output:

> True

What does happen:

> Traceback (most recent call last):
>   File "digraph.py", line 10, in <module>
>     print(nx.is_connected(g))
>   File "<decorator-gen-108>", line 2, in is_connected
>   File "/Users/daniel_kats/prog/cloud-trail-log-parsing/env/lib/python3.6/site-packages/networkx/utils/decorators.py", line 71, in _not_implemented_for
>     raise nx.NetworkXNotImplemented(msg)
> networkx.exception.NetworkXNotImplemented: not implemented for directed type

Would be very useful if someone implemented this

**Comment by boompig** [comment]
I guess this doesn't make a lot of sense for directed graphs.
