### ISSUE TITLE
set_node_attributes error

### ISSUE THREAD

**Issue by bakerwho** [networkx/networkx#2894]
```Traceback (most recent call last):
  File "~/anaconda3/lib/python3.6/site-packages/networkx/classes/function.py", line 647, in set_node_attributes
    for n, v in values.items():
AttributeError: 'str' object has no attribute 'items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/anaconda3/lib/python3.6/site-packages/networkx/classes/function.py", line 654, in set_node_attributes
    G.nodes[n][name] = values
TypeError: unhashable type: 'dict'
```
What's up with this?

**Comment by dschult** [comment]
The API for [the set_node_attributes function](https://networkx.github.io/documentation/stable/reference/generated/networkx.classes.function.set_node_attributes.html) changed to allow more flexibility. The order of values and name changed. It is probably best to be explicit about the order by using keywords:

    nx.set_node_attributes(G, values=values, name=name)
