### ISSUE TITLE
Networkx test giving an error

### ISSUE THREAD

**Issue by anusurendra** [networkx/networkx#2925]
Hi, 
I installed networkx using `sudo pip install networkx[all]` onto an Ubuntu 17.10 system. However, when I run the test:
```
>>> import networkx as nx
>>> nx.test()

```
the following error occurs:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "networkx/tests/test.py", line 24, in run
    "The nose package is needed to run the NetworkX tests.")
ImportError: The nose package is needed to run the NetworkX tests.
>>> 

```

**Comment by Dormir30** [comment]
Hi, did you install nose package ?
If you don't have nose package, this error happen.
Please check your installed package list
