### ISSUE TITLE
write pajek error (2)

### ISSUE THREAD

**Issue by sergio-gomez** [networkx/networkx#2945]
As previously reported, there is an error with the write_pajek() function. Here comes a simple example:

>>> import networkx as nx
>>> g = nx.path_graph(10)
>>> nx.write_pajek(g, "zzz.net")
>>> g2 = nx.read_pajek("zzz.net")
>>> nx.write_pajek(g2, "zzz2.net")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<decorator-gen-406>", line 2, in write_pajek
  File "/usr/lib/python3.6/site-packages/networkx/utils/decorators.py", line 227, in _open_file
    result = func_to_be_decorated(*new_args, **kwargs)
  File "/usr/lib/python3.6/site-packages/networkx/readwrite/pajek.py", line 107, in write_pajek
    for line in generate_pajek(G):
  File "/usr/lib/python3.6/site-packages/networkx/readwrite/pajek.py", line 66, in generate_pajek
    if v.strip() != '':
AttributeError: 'float' object has no attribute 'strip'

**Comment by dschult** [comment]
Where was this previously reported.
Is this fixed by #2936 ?

**Comment by sergio-gomez** [comment]
It was reported in #2933. I don't know if it was fixed, I'm just a user, not developer.
