### ISSUE TITLE
Examples expected to fail, but not failling: examples/advanced/plot_parallel_betweenness.py

### ISSUE THREAD

**Issue by sandrotosi** [networkx/networkx#2952]
Hello,
when building the doc for networkx/2.1 as downloaded by PyPI i get this error:

```copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 142 warnings.

Exception occurred:
  File "/usr/lib/python2.7/dist-packages/sphinx_gallery/gen_gallery.py", line 329, in sumarize_failing_examples
    "\n" + "-" * 79)
ValueError: Here is a summary of the problems encountered when running the examples

Examples expected to fail, but not failling:
Please remove these examples from
sphinx_gallery_conf['expected_failing_examples']
/home/morph/deb/build-area/python-networkx-2.1/examples/advanced/plot_parallel_betweenness.py
-------------------------------------------------------------------------------
The full traceback has been saved in /tmp/sphinx-err-5Xa_W9.log, if you want to report the issue to the developers.
```

content of that file is:

```
$  cat /tmp/sphinx-err-5Xa_W9.log
# Sphinx version: 1.6.6
# Python version: 2.7.14+ (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:
#   
#   copying static files...
#   done
#   copying extra files...
#   done
#   dumping search index in English (code: en) ...
#   done
#   dumping object inventory...
#   done
#   build succeeded, 142 warnings.
# Loaded extensions:
#   sphinx_gallery.gen_gallery (0.1.13) from /usr/lib/python2.7/dist-packages/sphinx_gallery/gen_gallery.pyc
#   sphinx.ext.mathjax (1.6.6) from /usr/lib/python2.7/dist-packages/sphinx/ext/mathjax.pyc
#   sphinx.ext.coverage (1.6.6) from /usr/lib/python2.7/dist-packages/sphinx/ext/coverage.pyc
#   sphinx.ext.viewcode (1.6.6) from /usr/lib/python2.7/dist-packages/sphinx/ext/viewcode.pyc
#   sphinx.ext.napoleon (1.6.6) from /usr/lib/python2.7/dist-packages/sphinx/ext/napoleon/__init__.pyc
#   sphinx.ext.todo (1.6.6) from /usr/lib/python2.7/dist-packages/sphinx/ext/todo.pyc
#   sphinx.ext.autodoc (1.6.6) from /usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.pyc
#   sphinx.ext.intersphinx (1.6.6) from /usr/lib/python2.7/dist-packages/sphinx/ext/intersphinx.pyc
#   sphinx.ext.doctest (1.6.6) from /usr/lib/python2.7/dist-packages/sphinx/ext/doctest.pyc
#   alabaster (0.7.8) from /usr/lib/python2.7/dist-packages/alabaster/__init__.pyc
#   nb2plots (unknown version) from /usr/lib/python2.7/dist-packages/nb2plots/__init__.pyc
#   texext (unknown version) from /usr/lib/python2.7/dist-packages/texext/__init__.pyc
#   sphinx.ext.autosummary (1.6.6) from /usr/lib/python2.7/dist-packages/sphinx/ext/autosummary/__init__.pyc
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 357, in build
    self.emit('build-finished', None)
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 489, in emit
    return self.events.emit(event, self, *args)
  File "/usr/lib/python2.7/dist-packages/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/usr/lib/python2.7/dist-packages/sphinx_gallery/gen_gallery.py", line 329, in sumarize_failing_examples
    "\n" + "-" * 79)
ValueError: Here is a summary of the problems encountered when running the examples

Examples expected to fail, but not failling:
Please remove these examples from
sphinx_gallery_conf['expected_failing_examples']
/home/morph/deb/build-area/python-networkx-2.1/examples/advanced/plot_parallel_betweenness.py
-------------------------------------------------------------------------------
```

**Comment by wuhaochen** [comment]
I think this is because pypi release doesn't have a README.txt in examples/advanced and therefore sphinx is not building there.

#2950 should have fixed this.
