### ISSUE TITLE
networkx/2.1: tests failures: test_agraph.TestAGraph.test_multi_directed + test_agraph.TestAGraph.test_multi_undirected

### ISSUE THREAD

**Issue by sandrotosi** [networkx/networkx#3003]
Hello,
when building networkx version 2.1 for debian we get the following unittest failures:

python2.7:
```
======================================================================
FAIL: test_agraph.TestAGraph.test_multi_directed
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/python-networkx-2.1/networkx/drawing/tests/test_agraph.py", line 69, in test_multi_directed
    self.agraph_checks(nx.MultiDiGraph())
  File "/build/python-networkx-2.1/networkx/drawing/tests/test_agraph.py", line 36, in agraph_checks
    self.assert_equal(G, H)
  File "/build/python-networkx-2.1/networkx/drawing/tests/test_agraph.py", line 29, in assert_equal
    assert_edges_equal(G1.edges(), G2.edges())
  File "/build/python-networkx-2.1/networkx/testing/utils.py", line 43, in assert_edges_equal
    assert_equal(c1, c2)
AssertionError: 4 != 3
    '4 != 3' = '%s != %s' % (safe_repr(4), safe_repr(3))
    '4 != 3' = self._formatMessage('4 != 3', '4 != 3')
>>  raise self.failureException('4 != 3')
    

======================================================================
FAIL: test_agraph.TestAGraph.test_multi_undirected
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/python-networkx-2.1/networkx/drawing/tests/test_agraph.py", line 66, in test_multi_undirected
    self.agraph_checks(nx.MultiGraph())
  File "/build/python-networkx-2.1/networkx/drawing/tests/test_agraph.py", line 36, in agraph_checks
    self.assert_equal(G, H)
  File "/build/python-networkx-2.1/networkx/drawing/tests/test_agraph.py", line 29, in assert_equal
    assert_edges_equal(G1.edges(), G2.edges())
  File "/build/python-networkx-2.1/networkx/testing/utils.py", line 43, in assert_edges_equal
    assert_equal(c1, c2)
AssertionError: 4 != 3
    '4 != 3' = '%s != %s' % (safe_repr(4), safe_repr(3))
    '4 != 3' = self._formatMessage('4 != 3', '4 != 3')
>>  raise self.failureException('4 != 3')
```

python3.6:
```
FAIL: test_agraph.TestAGraph.test_multi_directed
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/python-networkx-2.1/networkx/drawing/tests/test_agraph.py", line 69, in test_multi_directed
    self.agraph_checks(nx.MultiDiGraph())
  File "/build/python-networkx-2.1/networkx/drawing/tests/test_agraph.py", line 36, in agraph_checks
    self.assert_equal(G, H)
  File "/build/python-networkx-2.1/networkx/drawing/tests/test_agraph.py", line 29, in assert_equal
    assert_edges_equal(G1.edges(), G2.edges())
  File "/build/python-networkx-2.1/networkx/testing/utils.py", line 43, in assert_edges_equal
    assert_equal(c1, c2)
AssertionError: 4 != 3
    '4 != 3' = '%s != %s' % _common_shorten_repr(4, 3)
    '4 != 3' = self._formatMessage('4 != 3', '4 != 3')
>>  raise self.failureException('4 != 3')
    

======================================================================
FAIL: test_agraph.TestAGraph.test_multi_undirected
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/python-networkx-2.1/networkx/drawing/tests/test_agraph.py", line 66, in test_multi_undirected
    self.agraph_checks(nx.MultiGraph())
  File "/build/python-networkx-2.1/networkx/drawing/tests/test_agraph.py", line 36, in agraph_checks
    self.assert_equal(G, H)
  File "/build/python-networkx-2.1/networkx/drawing/tests/test_agraph.py", line 29, in assert_equal
    assert_edges_equal(G1.edges(), G2.edges())
  File "/build/python-networkx-2.1/networkx/testing/utils.py", line 43, in assert_edges_equal
    assert_equal(c1, c2)
AssertionError: 4 != 3
    '4 != 3' = '%s != %s' % _common_shorten_repr(4, 3)
    '4 != 3' = self._formatMessage('4 != 3', '4 != 3')
>>  raise self.failureException('4 != 3')
```

**Comment by sandrotosi** [comment]
graphviz version 2.40.1

**Comment by dschult** [comment]
My installs are using graphviz 2.36.
I'll try to get an environment set up to test this. I've got multiple versions of Graphviz, but can't easily tell which one pygraphviz is using...

Anybody know a quick way to have pygraphviz report which version of Graphviz it is using?

**Comment by hagberg** [comment]
This shows the version (and raises an error).
python -c "import pygraphviz; A = pygraphviz.AGraph(); A.layout('dot','-V')'
Would be a reasonable feature to add to pygraphivz.

**Comment by dschult** [comment]
Looking at #2852 again, I recall that the bug exists in Graphviz 2.40.1 but is fixed in the development version.  See https://github.com/pygraphviz/pygraphviz/issues/111

When Graphviz releases 2.42 we need to restrict to that or later. What can we do now? 
restrict to 2.38?

**Comment by hagberg** [comment]
Graphviz/pygraphviz issue resolved in later versions.
