### ISSUE TITLE
Segfault in writing to graphml

### ISSUE THREAD

**Issue by paulmelis** [networkx/networkx#3009]
```
#!/usr/bin/env python2
import networkx as nx
G = nx.Graph()
G.add_node(0, attr_dict=dict(x=0.0, y=0.0))
nx.write_graphml(G, 'doh.graphml')
```

```
./t_networkx_segfault.py 
Traceback (most recent call last):
  File "./t_networkx_segfault.py", line 5, in <module>
    nx.write_graphml(G, 'doh.graphml')
  File "<decorator-gen-440>", line 2, in write_graphml_lxml
  File "/usr/lib/python2.7/site-packages/networkx/utils/decorators.py", line 227, in _open_file
    result = func_to_be_decorated(*new_args, **kwargs)
  File "/usr/lib/python2.7/site-packages/networkx/readwrite/graphml.py", line 149, in write_graphml_lxml
    infer_numeric_types=infer_numeric_types)
  File "/usr/lib/python2.7/site-packages/networkx/readwrite/graphml.py", line 596, in __init__
    self.add_graph_element(graph)
  File "/usr/lib/python2.7/site-packages/networkx/readwrite/graphml.py", line 637, in add_graph_element
    T = self.xml_type[self.attr_type(k, "node", v)]
KeyError: <type 'dict'>
Segmentation fault (core dumped)
```

This is with 2.1 (Arch Linux package)

**Comment by dschult** [comment]
The ```attr_dict``` ketword argument to ```G.add_node``` is no longer supported in NetworkX v2.0+
(It now creates a node attribute called ```attr_dict```).  For recent NX versions you should use:

    G.add_node(0, x=0.0, y=0.0)
    #  or 
    G.add_node(0, **{x=0.0, y=0.0})

Of course, it'd be nice if the code didn't give a segfault!  On my system MacOS/anaconda, it gives the same KeyError without a segfault.

**Comment by paulmelis** [comment]
Argh, the top google hit for 'networkx add_node' gave me the docs for 1.10. Sorry....

**Comment by paulmelis** [comment]
Here's a related case, seems like the attribute type generated by the layout function (numpy.float64) causes `write_graphml` to segfault:

```
$ cat t_networkx_segfault.py 
#!/usr/bin/env python2
import networkx as nx
G = nx.Graph()
layout = None
G.add_node(0, x=0.0, y=0.0)
layout = nx.spring_layout(G, pos=layout)
x, y = layout[0]
print x, y
G.nodes[0]['x'] = x
G.nodes[0]['y'] = y

nx.write_graphml(G, 'doh.graphml')

$ ./t_networkx_segfault.py 
0.0 0.0
Traceback (most recent call last):
  File "./t_networkx_segfault.py", line 12, in <module>
    nx.write_graphml(G, 'doh.graphml')
  File "<decorator-gen-440>", line 2, in write_graphml_lxml
  File "/usr/lib/python2.7/site-packages/networkx/utils/decorators.py", line 227, in _open_file
    result = func_to_be_decorated(*new_args, **kwargs)
  File "/usr/lib/python2.7/site-packages/networkx/readwrite/graphml.py", line 149, in write_graphml_lxml
    infer_numeric_types=infer_numeric_types)
  File "/usr/lib/python2.7/site-packages/networkx/readwrite/graphml.py", line 596, in __init__
    self.add_graph_element(graph)
  File "/usr/lib/python2.7/site-packages/networkx/readwrite/graphml.py", line 637, in add_graph_element
    T = self.xml_type[self.attr_type(k, "node", v)]
KeyError: <type 'numpy.float64'>
Segmentation fault (core dumped)
```

**Comment by dschult** [comment]
Yes -- #2730 is an issue to try to improve the search engine results, but hasn't been implemented. I've notices that many packages have this problem of older versions coming up higher on the search list.
:}

**Comment by dschult** [comment]
Your new example also uses attribute types that aren't supported by ```write_graphml```.
It supports ```float``` but not ```numpy.float64```.  I'm not sure why t is segfaulting.

**Comment by paulmelis** [comment]
Right, casting the values to `float` fixes the segfault

**Comment by dschult** [comment]
Could you try a different installation of python to see if that fixes the segfaults?
I'm not familiar with Arch Linux, but it seems that this is a python issue rather than simply NetworkX.

**Comment by paulmelis** [comment]
Hmmm, looks like you are right, a segfault in the standard lxml.etree module:

```
$ gdb `which python2`
GNU gdb (GDB) 8.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/python2...(no debugging symbols found)...done.
(gdb) run t_networkx_segfault.py
Starting program: /usr/bin/python2 t_networkx_segfault.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
{0: array([0., 0.])}
Traceback (most recent call last):
  File "t_networkx_segfault.py", line 12, in <module>
    nx.write_graphml(G, 'doh.graphml')
  File "<decorator-gen-440>", line 2, in write_graphml_lxml
  File "/usr/lib/python2.7/site-packages/networkx/utils/decorators.py", line 227, in _open_file
    result = func_to_be_decorated(*new_args, **kwargs)
  File "/usr/lib/python2.7/site-packages/networkx/readwrite/graphml.py", line 149, in write_graphml_lxml
    infer_numeric_types=infer_numeric_types)
  File "/usr/lib/python2.7/site-packages/networkx/readwrite/graphml.py", line 596, in __init__
    self.add_graph_element(graph)
  File "/usr/lib/python2.7/site-packages/networkx/readwrite/graphml.py", line 637, in add_graph_element
    T = self.xml_type[self.attr_type(k, "node", v)]
KeyError: <type 'numpy.float64'>

Program received signal SIGSEGV, Segmentation fault.
0x00007fffe763fdbd in ?? () from /usr/lib/python2.7/site-packages/lxml/etree.so
(gdb) bt
#0  0x00007fffe763fdbd in ?? () from /usr/lib/python2.7/site-packages/lxml/etree.so
#1  0x00007fffe75fb4eb in ?? () from /usr/lib/python2.7/site-packages/lxml/etree.so
#2  0x00007fffe6daca3d in xmlOutputBufferFlush () from /usr/lib/libxml2.so.2
#3  0x00007fffe6daca9c in xmlOutputBufferClose () from /usr/lib/libxml2.so.2
#4  0x00007fffe753c64a in ?? () from /usr/lib/python2.7/site-packages/lxml/etree.so
#5  0x00007fffe753b574 in ?? () from /usr/lib/python2.7/site-packages/lxml/etree.so
#6  0x00007ffff74c83c0 in subtype_dealloc () from /usr/lib/libpython2.7.so.1.0
#7  0x00007ffff74a2557 in frame_dealloc.lto_priv () from /usr/lib/libpython2.7.so.1.0
#8  0x00007ffff7490c5c in tb_dealloc.lto_priv () from /usr/lib/libpython2.7.so.1.0
#9  0x00007ffff7490c22 in tb_dealloc.lto_priv () from /usr/lib/libpython2.7.so.1.0
#10 0x00007ffff7490c22 in tb_dealloc.lto_priv () from /usr/lib/libpython2.7.so.1.0
#11 0x00007ffff7490c22 in tb_dealloc.lto_priv () from /usr/lib/libpython2.7.so.1.0
#12 0x00007ffff7490c22 in tb_dealloc.lto_priv () from /usr/lib/libpython2.7.so.1.0
#13 0x00007ffff748362c in PyDict_SetItem () from /usr/lib/libpython2.7.so.1.0
#14 0x00007ffff747c4bf in PyDict_SetItemString () from /usr/lib/libpython2.7.so.1.0
#15 0x00007ffff74e74f9 in PyImport_Cleanup () from /usr/lib/libpython2.7.so.1.0
#16 0x00007ffff751da8b in Py_Finalize () from /usr/lib/libpython2.7.so.1.0
#17 0x00007ffff75126cc in Py_Main () from /usr/lib/libpython2.7.so.1.0
#18 0x00007ffff782106b in __libc_start_main () from /usr/lib/libc.so.6
#19 0x000055555555477a in _start ()
(gdb) 
```

**Comment by dschult** [comment]
OK.. I'll close this then -- people can still find it by searching.
