### ISSUE TITLE
Tests fail on python 3.7

### ISSUE THREAD

**Issue by eli-schwartz** [networkx/networkx#3046]
Arch Linux is currently trying to update to python 3.7.0, and while rebuilding all packages in our repositories, networkx failed the testsuite with the following log:

```
======================================================================
ERROR: test_edge_augmentation.test_null_graph
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/connectivity/tests/test_edge_augmentation.py", line 107, in test_null_graph
    _check_augmentations(G, max_k=MAX_EFFICIENT_K + 2)
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/connectivity/tests/test_edge_augmentation.py", line 440, in _check_augmentations
    max_aug_k=G.number_of_nodes() - 1)
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/connectivity/tests/test_edge_augmentation.py", line 316, in _augment_and_check
    G, k=k, weight=weight, partial=True, avail=avail))
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/connectivity/edge_augmentation.py", line 294, in k_edge_augmentation
    for edge in aug_edges:
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/connectivity/edge_augmentation.py", line 368, in partial_k_edge_augmentation
    k_edge_subgraphs = list(nx.k_edge_subgraphs(H, k=k))
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/connectivity/edge_kcomponents.py", line 201, in _k_edge_subgraphs_nodes
    for C in general_k_edge_subgraphs(G, k):
RuntimeError: generator raised StopIteration
-------------------- >> begin captured stdout << ---------------------
edges = []
nodes = []
aug_edges = []
info  = {'infeasible': True, 'failed': True}

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_edge_augmentation.test_cliques
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/connectivity/tests/test_edge_augmentation.py", line 113, in test_cliques
    _check_augmentations(G, max_k=MAX_EFFICIENT_K + 2)
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/connectivity/tests/test_edge_augmentation.py", line 440, in _check_augmentations
    max_aug_k=G.number_of_nodes() - 1)
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/connectivity/tests/test_edge_augmentation.py", line 316, in _augment_and_check
    G, k=k, weight=weight, partial=True, avail=avail))
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/connectivity/edge_augmentation.py", line 294, in k_edge_augmentation
    for edge in aug_edges:
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/connectivity/edge_augmentation.py", line 368, in partial_k_edge_augmentation
    k_edge_subgraphs = list(nx.k_edge_subgraphs(H, k=k))
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/connectivity/edge_kcomponents.py", line 201, in _k_edge_subgraphs_nodes
    for C in general_k_edge_subgraphs(G, k):
RuntimeError: generator raised StopIteration
-------------------- >> begin captured stdout << ---------------------
edges = []
nodes = [0]
aug_edges = []
info  = {'infeasible': True, 'failed': True}

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_edge_augmentation.test_clique_and_node
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/connectivity/tests/test_edge_augmentation.py", line 120, in test_clique_and_node
    _check_augmentations(G, max_k=MAX_EFFICIENT_K + 2)
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/connectivity/tests/test_edge_augmentation.py", line 440, in _check_augmentations
    max_aug_k=G.number_of_nodes() - 1)
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/connectivity/tests/test_edge_augmentation.py", line 316, in _augment_and_check
    G, k=k, weight=weight, partial=True, avail=avail))
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/connectivity/edge_augmentation.py", line 294, in k_edge_augmentation
    for edge in aug_edges:
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/connectivity/edge_augmentation.py", line 368, in partial_k_edge_augmentation
    k_edge_subgraphs = list(nx.k_edge_subgraphs(H, k=k))
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/connectivity/edge_kcomponents.py", line 201, in _k_edge_subgraphs_nodes
    for C in general_k_edge_subgraphs(G, k):
RuntimeError: generator raised StopIteration
-------------------- >> begin captured stdout << ---------------------
edges = []
nodes = [0, 2]
aug_edges = []
info  = {'infeasible': True, 'failed': True}

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_edge_augmentation.test_point_graph
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/connectivity/tests/test_edge_augmentation.py", line 126, in test_point_graph
    _check_augmentations(G, max_k=MAX_EFFICIENT_K + 2)
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/connectivity/tests/test_edge_augmentation.py", line 440, in _check_augmentations
    max_aug_k=G.number_of_nodes() - 1)
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/connectivity/tests/test_edge_augmentation.py", line 316, in _augment_and_check
    G, k=k, weight=weight, partial=True, avail=avail))
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/connectivity/edge_augmentation.py", line 294, in k_edge_augmentation
    for edge in aug_edges:
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/connectivity/edge_augmentation.py", line 368, in partial_k_edge_augmentation
    k_edge_subgraphs = list(nx.k_edge_subgraphs(H, k=k))
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/connectivity/edge_kcomponents.py", line 201, in _k_edge_subgraphs_nodes
    for C in general_k_edge_subgraphs(G, k):
RuntimeError: generator raised StopIteration
-------------------- >> begin captured stdout << ---------------------
edges = []
nodes = [1]
aug_edges = []
info  = {'infeasible': True, 'failed': True}

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_edge_augmentation.test_shell
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/connectivity/tests/test_edge_augmentation.py", line 196, in test_shell
    _check_augmentations(G)
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/connectivity/tests/test_edge_augmentation.py", line 431, in _check_augmentations
    G, k=k,  verbose=verbose, orig_k=orig_k)
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/connectivity/tests/test_edge_augmentation.py", line 287, in _augment_and_check
    for edge in generator:
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/connectivity/edge_augmentation.py", line 282, in k_edge_augmentation
    for edge in list(aug_edges):
RuntimeError: generator raised StopIteration
-------------------- >> begin captured stdout << ---------------------
edges = [(0, 6), (0, 1), (0, 9), (0, 2), (0, 8), (0, 5), (0, 10), (0, 4), (0, 12), (1, 8), (1, 10), (1, 4), (1, 6), (1, 7), (1, 11), (1, 2), (1, 3), (1, 5), (2, 6), (2, 4), (2, 11), (2, 7), (2, 9), (2, 3), (2, 8), (3, 7), (3, 10), (3, 11), (3, 4), (3, 9), (3, 8), (3, 5), (3, 19), (3, 24), (3, 15), (3, 21), (4, 6), (4, 8), (4, 9), (4, 7), (4, 5), (4, 11), (4, 10), (4, 12), (5, 7), (5, 6), (5, 8), (5, 10), (5, 11), (5, 9), (5, 24), (6, 10), (6, 9), (6, 8), (6, 11), (6, 7), (6, 15), (6, 14), (7, 8), (7, 11), (7, 13), (8, 9), (8, 10), (8, 11), (9, 11), (9, 10), (9, 17), (10, 22), (10, 17), (11, 14), (12, 23), (12, 19), (12, 14), (12, 26), (12, 15), (12, 25), (12, 13), (14, 15), (14, 24), (15, 18), (15, 20), (16, 20), (16, 19), (16, 24), (18, 22), (18, 20), (20, 22), (21, 24), (21, 25), (22, 26), (22, 23), (23, 24), (24, 26), (25, 26)]
nodes = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]
aug_edges = []
info  = {'failed': True}

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_edge_kcomponents.test_empty_input
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/connectivity/edge_kcomponents.py", line 576, in general_k_edge_subgraphs
    raise StopIteration()
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/connectivity/tests/test_edge_kcomponents.py", line 158, in test_empty_input
    assert_equal([], list(nx.k_edge_subgraphs(G, k=5)))
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/connectivity/edge_kcomponents.py", line 201, in _k_edge_subgraphs_nodes
    for C in general_k_edge_subgraphs(G, k):
RuntimeError: generator raised StopIteration

======================================================================
ERROR: test_edgedfs.TestEdgeDFS.test_empty
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/traversal/edgedfs.py", line 155, in edge_dfs
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/algorithms/traversal/tests/test_edgedfs.py", line 26, in test_empty
    edges = list(edge_dfs(G))
RuntimeError: generator raised StopIteration

======================================================================
ERROR: test_classic.TestGeneratorClassic.test_full_rary_tree_empty
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/generators/classic.py", line 60, in _tree_edges
    parents = [next(nodes)]  # stack of max length r
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/generators/tests/test_classic.py", line 81, in test_full_rary_tree_empty
    t = full_rary_tree(3, 0)
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/generators/classic.py", line 102, in full_rary_tree
    G.add_edges_from(_tree_edges(n, r))
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/classes/graph.py", line 925, in add_edges_from
    for e in ebunch_to_add:
RuntimeError: generator raised StopIteration

======================================================================
ERROR: test_sparse6.TestSparseGraph6.test_from_sparse6_bytes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/readwrite/sparse6.py", line 166, in parseData
    d = next(chunks)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/readwrite/tests/test_sparse6.py", line 17, in test_from_sparse6_bytes
    G = nx.from_sparse6_bytes(data)
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/readwrite/sparse6.py", line 188, in from_sparse6_bytes
    for b, x in parseData():
RuntimeError: generator raised StopIteration

======================================================================
ERROR: test_sparse6.TestSparseGraph6.test_read_many_graph6
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/readwrite/sparse6.py", line 166, in parseData
    d = next(chunks)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/readwrite/tests/test_sparse6.py", line 49, in test_read_many_graph6
    glist = nx.read_sparse6(fh)
  File "<decorator-gen-424>", line 2, in read_sparse6
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/utils/decorators.py", line 227, in _open_file
    result = func_to_be_decorated(*new_args, **kwargs)
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/readwrite/sparse6.py", line 311, in read_sparse6
    glist.append(from_sparse6_bytes(line))
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/readwrite/sparse6.py", line 188, in from_sparse6_bytes
    for b, x in parseData():
RuntimeError: generator raised StopIteration

======================================================================
ERROR: test_sparse6.TestSparseGraph6.test_read_sparse6
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/readwrite/sparse6.py", line 166, in parseData
    d = next(chunks)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/readwrite/tests/test_sparse6.py", line 38, in test_read_sparse6
    G = nx.from_sparse6_bytes(data)
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/readwrite/sparse6.py", line 188, in from_sparse6_bytes
    for b, x in parseData():
RuntimeError: generator raised StopIteration

======================================================================
ERROR: test_read_write_inverse (test_sparse6.TestWriteSparse6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/readwrite/sparse6.py", line 166, in parseData
    d = next(chunks)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/readwrite/tests/test_sparse6.py", line 130, in test_read_write_inverse
    g2 = nx.from_sparse6_bytes(gstr)
  File "/build/python-networkx/src/networkx-networkx-2.1/networkx/readwrite/sparse6.py", line 188, in from_sparse6_bytes
    for b, x in parseData():
RuntimeError: generator raised StopIteration

----------------------------------------------------------------------
Ran 3055 tests in 85.953s

FAILED (SKIP=60, errors=12)
```

**Comment by yan12125** [comment]
Following suggestions in [PEP-479](https://www.python.org/dev/peps/pep-0479/):

> This is done by enclosing those places in the generator body where a StopIteration is expected (e.g. bare next() calls or in some cases helper functions that are expected to raise StopIteration) in a try/except construct that returns when StopIteration is raised. The try/except construct should appear directly in the generator function; doing this in a helper function that is not itself a generator does not work. If raise StopIteration occurs directly in a generator, simply replace it with return.

I managed to patch networkx to fix tests. For version 2.1:
```Diff
diff --git a/networkx/algorithms/connectivity/edge_augmentation.py b/networkx/algorithms/connectivity/edge_augmentation.py
index cd8c748f..525feff9 100644
--- a/networkx/algorithms/connectivity/edge_augmentation.py
+++ b/networkx/algorithms/connectivity/edge_augmentation.py
@@ -813,7 +813,10 @@ def unconstrained_bridge_augmentation(G):
         A2 = [tuple(leafs)]
     else:
         # Choose an arbitrary non-leaf root
-        root = next(n for n, d in T.degree() if d > 1)
+        try:
+            root = next(n for n, d in T.degree() if d > 1)
+        except StopIteration:
+            return
         # order the leaves of C by (induced directed) preorder
         v2 = [n for n in nx.dfs_preorder_nodes(T, root) if T.degree(n) == 1]
         # connecting first half of the leafs in pre-order to the second
@@ -954,7 +957,10 @@ def weighted_bridge_augmentation(G, avail, weight=None):
     #     nx.least_common_ancestor on the reversed Tree.
 
     # Pick an arbitrary leaf from C as the root
-    root = next(n for n in C.nodes() if C.degree(n) == 1)
+    try:
+        root = next(n for n in C.nodes() if C.degree(n) == 1)
+    except StopIteration:
+        return
     # Root C into a tree TR by directing all edges away from the root
     # Note in their paper T directs edges towards the root
     TR = nx.dfs_tree(C, root)
@@ -1230,7 +1236,7 @@ def greedy_k_edge_augmentation(G, k, avail=None, weight=None, seed=None):
 
     done = is_k_edge_connected(G, k)
     if done:
-        raise StopIteration()
+        return
     if avail is None:
         # all edges are available
         avail_uv = list(complement_edges(G))
diff --git a/networkx/algorithms/connectivity/edge_kcomponents.py b/networkx/algorithms/connectivity/edge_kcomponents.py
index 37bf61dc..f9b4364c 100644
--- a/networkx/algorithms/connectivity/edge_kcomponents.py
+++ b/networkx/algorithms/connectivity/edge_kcomponents.py
@@ -573,7 +573,7 @@ def general_k_edge_subgraphs(G, k):
     if G.number_of_nodes() < k:
         for node in G.nodes():
             yield G.subgraph([node]).copy()
-        raise StopIteration()
+        return
 
     # Intermediate results
     R0 = {G.subgraph(cc).copy() for cc in find_ccs(G)}
diff --git a/networkx/algorithms/traversal/edgedfs.py b/networkx/algorithms/traversal/edgedfs.py
index 5434057d..b9d442b6 100644
--- a/networkx/algorithms/traversal/edgedfs.py
+++ b/networkx/algorithms/traversal/edgedfs.py
@@ -152,7 +152,7 @@ def edge_dfs(G, source=None, orientation='original'):
     """
     nodes = list(G.nbunch_iter(source))
     if not nodes:
-        raise StopIteration
+        return
 
     kwds = {'data': False}
     if G.is_multigraph():
diff --git a/networkx/generators/classic.py b/networkx/generators/classic.py
index 22741a37..3338db36 100644
--- a/networkx/generators/classic.py
+++ b/networkx/generators/classic.py
@@ -57,7 +57,10 @@ def _tree_edges(n, r):
     # helper function for trees
     # yields edges in rooted tree at 0 with n nodes and branching ratio r
     nodes = iter(range(n))
-    parents = [next(nodes)]  # stack of max length r
+    try:
+        parents = [next(nodes)]  # stack of max length r
+    except StopIteration:
+        return
     while parents:
         source = parents.pop(0)
         for i in range(r):
diff --git a/networkx/readwrite/sparse6.py b/networkx/readwrite/sparse6.py
index 00ccae60..6f404ca3 100644
--- a/networkx/readwrite/sparse6.py
+++ b/networkx/readwrite/sparse6.py
@@ -163,7 +163,10 @@ def from_sparse6_bytes(string):
 
         while 1:
             if dLen < 1:
-                d = next(chunks)
+                try:
+                    d = next(chunks)
+                except StopIteration:
+                    return
                 dLen = 6
             dLen -= 1
             b = (d >> dLen) & 1  # grab top remaining bit
@@ -171,7 +174,10 @@ def from_sparse6_bytes(string):
             x = d & ((1 << dLen) - 1)  # partially built up value of x
             xLen = dLen		# how many bits included so far in x
             while xLen < k:  # now grab full chunks until we have enough
-                d = next(chunks)
+                try:
+                    d = next(chunks)
+                except StopIteration:
+                    return
                 dLen = 6
                 x = (x << 6) + d
                 xLen += 6
```
On master, an extra patch is needed:
```Diff
diff --git a/networkx/algorithms/traversal/edgebfs.py b/networkx/algorithms/traversal/edgebfs.py
index 19260899..959ad4c0 100644
--- a/networkx/algorithms/traversal/edgebfs.py
+++ b/networkx/algorithms/traversal/edgebfs.py
@@ -96,7 +96,7 @@ def edge_bfs(G, source=None, orientation=None):
     """
     nodes = list(G.nbunch_iter(source))
     if not nodes:
-        raise StopIteration
+        return

     directed = G.is_directed()
     kwds = {'data': False}
```

**Comment by dschult** [comment]
Thanks for checking into python 3.7 and reporting the problems -- 
And thanks for finding solutions.  This should be doable. :)

**Comment by dschult** [comment]
I can't seem to build a good testbed for python 3.7. And I don't have travis doing it correctly either. 

Can you check if this PR makes NX work on Arch Linux? Suggestions for getting a working testbed would be helpful too. :)

**Comment by eli-schwartz** [comment]
I backported this patch right away, see https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/python-networkx&id=4e8358011880e00e693bf0012472b4b3d7ef4286

Here's the successful build logs:
https://pkgbuild.com/~eschwartz/python-networkx/

The one named *-check.log is the log for running the testsuite.

You may also use an Arch Linux system with the [staging repositories enabled](https://wiki.archlinux.org/index.php/Official_repositories#staging). As our rather strongly-worded wiki indicates, this is generally a bad move, though in this case since you specifically want to test python-networkx using python3.7 in a temporary testbed, it's probably not so bad. :D

It is of course the environment I used to rebuild our package. :)

**Comment by dschult** [comment]
Great!  Thanks very much for this!
