### ISSUE TITLE
test_subgraph.TestSubgraph.test_subgraph_centrality_big_graph leads to crash of the interpreter on i586 (from time to time)

### ISSUE THREAD

**Issue by mcepl** [networkx/networkx#3304]
Not sure, what's going on but often (not always) ``test_subgraph.TestSubgraph.test_subgraph_centrality_big_graph`` fails on i586 machine when being tested by building of the openSUSE package with:
```
test_subgraph.TestSubgraph.test_subgraph_centrality_big_graph ... /var/tmp/rpm-tmp.DC2Gnh: line 37:  4947 Segmentation fault      /usr/bin/python2 setup.py test
```
[Full build log](https://github.com/networkx/networkx/files/2764077/python-networkx-i586-log.txt)

**Comment by mcepl** [comment]
I have captured this backtrace:
```
Thread 8 "python3" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xec18ab40 (LWP 19932)]
inner_thread (args=0xfffb5f30, range_m=0xfffb5f70, range_n=0xfffb6078, sa=0xea98a020, sb=0xeaa86020, mypos=7) at level3_thread.c:281
281	level3_thread.c: No such file or directory.
(gdb) t a a bt

Thread 8 (Thread 0xec18ab40 (LWP 19932)):
#0  inner_thread (args=0xfffb5f30, range_m=0xfffb5f70, range_n=0xfffb6078, sa=0xea98a020, sb=0xeaa86020, mypos=7) at level3_thread.c:281
#1  0xf573d5dc in blas_thread_server (arg=0x6) at blas_server.c:433
#2  0xf7fb424d in start_thread (arg=0xec18ab40) at pthread_create.c:463
#3  0xf7ef0146 in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:108

Thread 7 (Thread 0xed98bb40 (LWP 19931)):
#0  0xf7ed4347 in sched_yield () at ../sysdeps/unix/syscall-template.S:78
#1  0xf563f618 in inner_thread (args=0xfffb5f30, range_m=0xfffb5f70, range_n=0xfffb6078, sa=<optimized out>, sb=<optimized out>, mypos=<optimized out>) at level3_thread.c:416
#2  0xf573d5dc in blas_thread_server (arg=0x5) at blas_server.c:433
#3  0xf7fb424d in start_thread (arg=0xed98bb40) at pthread_create.c:463
#4  0xf7ef0146 in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:108

Thread 6 (Thread 0xef18cb40 (LWP 19930)):
#0  inner_thread (args=0xfffb5f30, range_m=0xfffb5f70, range_n=0xfffb6078, sa=0xed98c020, sb=0xeda88020, mypos=5) at level3_thread.c:281
#1  0xf573d5dc in blas_thread_server (arg=0x4) at blas_server.c:433
#2  0xf7fb424d in start_thread (arg=0xef18cb40) at pthread_create.c:463
#3  0xf7ef0146 in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:108

Thread 5 (Thread 0xf198db40 (LWP 19929)):
#0  0xf7ed4347 in sched_yield () at ../sysdeps/unix/syscall-template.S:78
#1  0xf563f618 in inner_thread (args=0xfffb5f30, range_m=0xfffb5f70, range_n=0xfffb6078, sa=<optimized out>, sb=<optimized out>, mypos=<optimized out>) at level3_thread.c:416
#2  0xf573d5dc in blas_thread_server (arg=0x3) at blas_server.c:433
#3  0xf7fb424d in start_thread (arg=0xf198db40) at pthread_create.c:463
#4  0xf7ef0146 in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:108

Thread 4 (Thread 0xf318eb40 (LWP 19928)):
#0  inner_thread (args=0xfffb5f30, range_m=0xfffb5f70, range_n=0xfffb6078, sa=0xf018d020, sb=0xf0289020, mypos=3) at level3_thread.c:281
#1  0xf573d5dc in blas_thread_server (arg=0x2) at blas_server.c:433
#2  0xf7fb424d in start_thread (arg=0xf318eb40) at pthread_create.c:463
#3  0xf7ef0146 in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:108

Thread 3 (Thread 0xf498fb40 (LWP 19927)):
#0  0xf7ed4347 in sched_yield () at ../sysdeps/unix/syscall-template.S:78
#1  0xf563f618 in inner_thread (args=0xfffb5f30, range_m=0xfffb5f70, range_n=0xfffb6078, sa=<optimized out>, sb=<optimized out>, mypos=<optimized out>) at level3_thread.c:416
#2  0xf573d5dc in blas_thread_server (arg=0x1) at blas_server.c:433
#3  0xf7fb424d in start_thread (arg=0xf498fb40) at pthread_create.c:463
#4  0xf7ef0146 in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:108

Thread 2 (Thread 0xf5190b40 (LWP 19926)):
#0  inner_thread (args=0xfffb5f30, range_m=0xfffb5f70, range_n=0xfffb6078, sa=0xf318f020, sb=0xf328b020, mypos=1) at level3_thread.c:281
#1  0xf573d5dc in blas_thread_server (arg=0x0) at blas_server.c:433
#2  0xf7fb424d in start_thread (arg=0xf5190b40) at pthread_create.c:463
#3  0xf7ef0146 in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:108

Thread 1 (Thread 0xf7997700 (LWP 19921)):
#0  0xf7ed4347 in sched_yield () at ../sysdeps/unix/syscall-template.S:78
#1  0xf563f618 in inner_thread (args=0xfffb5f30, range_m=0xfffb5f70, range_n=0xfffb6078, sa=<optimized out>, sb=<optimized out>, mypos=<optimized out>) at level3_thread.c:416
#2  0xf573dd64 in exec_blas (queue=0xfffb617c, num=8) at blas_server.c:826
#3  exec_blas (num=8, queue=0xfffb617c) at blas_server.c:781
--Type <RET> for more, q to quit, c to continue without paging--
#4  0xf563ed7b in gemm_driver (args=args@entry=0xffff7f30, range_m=range_m@entry=0x0, range_n=<optimized out>, sa=0xe7bf9020, sb=0xe7cf5020, nthreads_m=8, nthreads_n=1)
    at level3_thread.c:706
#5  0xf563f882 in dgemm_thread_tn (args=0xffff7f30, range_m=0x0, range_n=0x0, sa=0xe7bf9020, sb=0xe7cf5020, mypos=0) at level3_thread.c:763
#6  0xf5558196 in dgemm_ (TRANSA=0xf66dc420 "TransposeNon-unitUpper", TRANSB=0xf66dc404 "No transposeLowerRight", M=0xffff8140, N=0xffff8134, K=0xffff8034, alpha=0xf66dc3f8, 
    a=0xe8bfa088, ldA=0xffff83f8, b=0xe8cbd918, ldB=0xffff840c, beta=0xf66dc3f8, c=0xe8c47208, ldC=0xffff8138) at gemm.c:442
#7  0xf615aafb in dlarfb (side=..., trans=..., direct=..., storev=..., m=102, n=199, k=32, v=..., ldv=199, t=..., ldt=65, c=..., ldc=199, work=..., ldwork=199, _side=1, _trans=1, 
    _direct=7, _storev=10) at dlarfb.f:273
#8  0xf617526d in dormqr (side=..., trans=..., m=198, n=199, k=198, a=..., lda=199, tau=..., c=..., ldc=199, work=..., lwork=40398, info=0, _side=1, _trans=1) at dormqr.f:332
#9  0xf61771a7 in dormtr (side=..., uplo=..., trans=..., m=199, n=199, a=..., lda=199, tau=..., c=..., ldc=199, work=..., lwork=40398, info=0, _side=1, _uplo=1, _trans=1)
    at dormtr.f:303
#10 0xf61961e9 in dsyevd (jobz=..., uplo=..., n=199, a=..., lda=199, w=..., work=..., lwork=80397, iwork=..., liwork=998, info=0, _jobz=-156812478, _uplo=-361201664) at dsyevd.f:341
#11 0xea7754fd in DOUBLE_eigh_wrapper () from /usr/lib/python3.6/site-packages/numpy/linalg/_umath_linalg.cpython-36m-i386-linux-gnu.so
#12 0xea9032fa in PyUFunc_GeneralizedFunction () from /usr/lib/python3.6/site-packages/numpy/core/umath.cpython-36m-i386-linux-gnu.so
#13 0xea907171 in PyUFunc_GenericFunction () from /usr/lib/python3.6/site-packages/numpy/core/umath.cpython-36m-i386-linux-gnu.so
#14 0xea908014 in ufunc_generic_call () from /usr/lib/python3.6/site-packages/numpy/core/umath.cpython-36m-i386-linux-gnu.so
#15 0xf7b826db in _PyObject_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#16 0xf7bef5d6 in _PyObject_FastCallKeywords () from /usr/lib/libpython3.6m.so.1.0
#17 0xf7bfd615 in call_function () from /usr/lib/libpython3.6m.so.1.0
#18 0xf7c2cf84 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.6m.so.1.0
#19 0xf7b81020 in _PyEval_EvalCodeWithName () from /usr/lib/libpython3.6m.so.1.0
#20 0xf7bb91cf in fast_function () from /usr/lib/libpython3.6m.so.1.0
#21 0xf7bfd57a in call_function () from /usr/lib/libpython3.6m.so.1.0
#22 0xf7c2c1e5 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.6m.so.1.0
#23 0xf7bff9b4 in PyEval_EvalCodeEx () from /usr/lib/libpython3.6m.so.1.0
#24 0xf7c009d5 in function_call () from /usr/lib/libpython3.6m.so.1.0
#25 0xf7b82d24 in PyObject_Call () from /usr/lib/libpython3.6m.so.1.0
#26 0xf7c2d912 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.6m.so.1.0
#27 0xf7b81020 in _PyEval_EvalCodeWithName () from /usr/lib/libpython3.6m.so.1.0
#28 0xf7bb91cf in fast_function () from /usr/lib/libpython3.6m.so.1.0
#29 0xf7bfd57a in call_function () from /usr/lib/libpython3.6m.so.1.0
#30 0xf7c2c1e5 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.6m.so.1.0
#31 0xf7bff9b4 in PyEval_EvalCodeEx () from /usr/lib/libpython3.6m.so.1.0
#32 0xf7c009d5 in function_call () from /usr/lib/libpython3.6m.so.1.0
#33 0xf7b82d24 in PyObject_Call () from /usr/lib/libpython3.6m.so.1.0
#34 0xf7c2d912 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.6m.so.1.0
#35 0xf7b81020 in _PyEval_EvalCodeWithName () from /usr/lib/libpython3.6m.so.1.0
#36 0xf7bb91cf in fast_function () from /usr/lib/libpython3.6m.so.1.0
#37 0xf7bfd57a in call_function () from /usr/lib/libpython3.6m.so.1.0
#38 0xf7c2c1e5 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.6m.so.1.0
#39 0xf7bb8fdf in fast_function () from /usr/lib/libpython3.6m.so.1.0
#40 0xf7bfd57a in call_function () from /usr/lib/libpython3.6m.so.1.0
#41 0xf7c2c1e5 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.6m.so.1.0
#42 0xf7b81faf in _PyFunction_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#43 0xf7b82925 in _PyObject_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#44 0xf7b8e07e in _PyObject_Call_Prepend () from /usr/lib/libpython3.6m.so.1.0
#45 0xf7b8e14f in method_call () from /usr/lib/libpython3.6m.so.1.0
#46 0xf7b82d24 in PyObject_Call () from /usr/lib/libpython3.6m.so.1.0
#47 0xf7c2d912 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.6m.so.1.0
#48 0xf7bb8fdf in fast_function () from /usr/lib/libpython3.6m.so.1.0
#49 0xf7bfd57a in call_function () from /usr/lib/libpython3.6m.so.1.0
#50 0xf7c2c1e5 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.6m.so.1.0
--Type <RET> for more, q to quit, c to continue without paging--
#51 0xf7b81020 in _PyEval_EvalCodeWithName () from /usr/lib/libpython3.6m.so.1.0
#52 0xf7b823b3 in _PyFunction_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#53 0xf7b82925 in _PyObject_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#54 0xf7b8e07e in _PyObject_Call_Prepend () from /usr/lib/libpython3.6m.so.1.0
#55 0xf7b8e14f in method_call () from /usr/lib/libpython3.6m.so.1.0
#56 0xf7b82d24 in PyObject_Call () from /usr/lib/libpython3.6m.so.1.0
#57 0xf7c2d912 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.6m.so.1.0
#58 0xf7b81020 in _PyEval_EvalCodeWithName () from /usr/lib/libpython3.6m.so.1.0
#59 0xf7b821a8 in _PyFunction_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#60 0xf7b82925 in _PyObject_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#61 0xf7b8e07e in _PyObject_Call_Prepend () from /usr/lib/libpython3.6m.so.1.0
#62 0xf7b8e14f in method_call () from /usr/lib/libpython3.6m.so.1.0
#63 0xf7b82d24 in PyObject_Call () from /usr/lib/libpython3.6m.so.1.0
#64 0xf7bf4644 in slot_tp_call () from /usr/lib/libpython3.6m.so.1.0
#65 0xf7b826db in _PyObject_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#66 0xf7bef55a in _PyObject_FastCallKeywords () from /usr/lib/libpython3.6m.so.1.0
#67 0xf7bfd615 in call_function () from /usr/lib/libpython3.6m.so.1.0
#68 0xf7c2c1e5 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.6m.so.1.0
#69 0xf7bb8fdf in fast_function () from /usr/lib/libpython3.6m.so.1.0
#70 0xf7bfd57a in call_function () from /usr/lib/libpython3.6m.so.1.0
#71 0xf7c2c1e5 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.6m.so.1.0
#72 0xf7b81faf in _PyFunction_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#73 0xf7b82925 in _PyObject_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#74 0xf7b8e07e in _PyObject_Call_Prepend () from /usr/lib/libpython3.6m.so.1.0
#75 0xf7b8e14f in method_call () from /usr/lib/libpython3.6m.so.1.0
#76 0xf7b82d24 in PyObject_Call () from /usr/lib/libpython3.6m.so.1.0
#77 0xf7c2d912 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.6m.so.1.0
#78 0xf7b81020 in _PyEval_EvalCodeWithName () from /usr/lib/libpython3.6m.so.1.0
#79 0xf7b821a8 in _PyFunction_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#80 0xf7b82925 in _PyObject_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#81 0xf7b8e07e in _PyObject_Call_Prepend () from /usr/lib/libpython3.6m.so.1.0
#82 0xf7b8e14f in method_call () from /usr/lib/libpython3.6m.so.1.0
#83 0xf7b82d24 in PyObject_Call () from /usr/lib/libpython3.6m.so.1.0
#84 0xf7bf4644 in slot_tp_call () from /usr/lib/libpython3.6m.so.1.0
#85 0xf7b826db in _PyObject_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#86 0xf7bef55a in _PyObject_FastCallKeywords () from /usr/lib/libpython3.6m.so.1.0
#87 0xf7bfd615 in call_function () from /usr/lib/libpython3.6m.so.1.0
#88 0xf7c2c1e5 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.6m.so.1.0
#89 0xf7b81faf in _PyFunction_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#90 0xf7b82925 in _PyObject_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#91 0xf7b8e07e in _PyObject_Call_Prepend () from /usr/lib/libpython3.6m.so.1.0
#92 0xf7b8e14f in method_call () from /usr/lib/libpython3.6m.so.1.0
#93 0xf7b82d24 in PyObject_Call () from /usr/lib/libpython3.6m.so.1.0
#94 0xf7c2d912 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.6m.so.1.0
#95 0xf7b81020 in _PyEval_EvalCodeWithName () from /usr/lib/libpython3.6m.so.1.0
#96 0xf7b821a8 in _PyFunction_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#97 0xf7b82925 in _PyObject_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#98 0xf7b8e07e in _PyObject_Call_Prepend () from /usr/lib/libpython3.6m.so.1.0
#99 0xf7b8e14f in method_call () from /usr/lib/libpython3.6m.so.1.0
#100 0xf7b82d24 in PyObject_Call () from /usr/lib/libpython3.6m.so.1.0
#101 0xf7bf4644 in slot_tp_call () from /usr/lib/libpython3.6m.so.1.0
--Type <RET> for more, q to quit, c to continue without paging--
#102 0xf7b826db in _PyObject_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#103 0xf7bef55a in _PyObject_FastCallKeywords () from /usr/lib/libpython3.6m.so.1.0
#104 0xf7bfd615 in call_function () from /usr/lib/libpython3.6m.so.1.0
#105 0xf7c2c1e5 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.6m.so.1.0
#106 0xf7b81faf in _PyFunction_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#107 0xf7b82925 in _PyObject_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#108 0xf7b8e07e in _PyObject_Call_Prepend () from /usr/lib/libpython3.6m.so.1.0
#109 0xf7b8e14f in method_call () from /usr/lib/libpython3.6m.so.1.0
#110 0xf7b82d24 in PyObject_Call () from /usr/lib/libpython3.6m.so.1.0
#111 0xf7c2d912 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.6m.so.1.0
#112 0xf7b81020 in _PyEval_EvalCodeWithName () from /usr/lib/libpython3.6m.so.1.0
#113 0xf7b821a8 in _PyFunction_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#114 0xf7b82925 in _PyObject_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#115 0xf7b8e07e in _PyObject_Call_Prepend () from /usr/lib/libpython3.6m.so.1.0
#116 0xf7b8e14f in method_call () from /usr/lib/libpython3.6m.so.1.0
#117 0xf7b82d24 in PyObject_Call () from /usr/lib/libpython3.6m.so.1.0
#118 0xf7bf4644 in slot_tp_call () from /usr/lib/libpython3.6m.so.1.0
#119 0xf7b826db in _PyObject_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#120 0xf7bef55a in _PyObject_FastCallKeywords () from /usr/lib/libpython3.6m.so.1.0
#121 0xf7bfd615 in call_function () from /usr/lib/libpython3.6m.so.1.0
#122 0xf7c2c1e5 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.6m.so.1.0
#123 0xf7bb8fdf in fast_function () from /usr/lib/libpython3.6m.so.1.0
#124 0xf7bfd57a in call_function () from /usr/lib/libpython3.6m.so.1.0
#125 0xf7c2c1e5 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.6m.so.1.0
#126 0xf7bb8fdf in fast_function () from /usr/lib/libpython3.6m.so.1.0
#127 0xf7bfd57a in call_function () from /usr/lib/libpython3.6m.so.1.0
#128 0xf7c2c1e5 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.6m.so.1.0
#129 0xf7c00059 in PyEval_EvalCodeEx () from /usr/lib/libpython3.6m.so.1.0
#130 0xf7c009d5 in function_call () from /usr/lib/libpython3.6m.so.1.0
#131 0xf7b82d24 in PyObject_Call () from /usr/lib/libpython3.6m.so.1.0
#132 0xf7c2d912 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.6m.so.1.0
#133 0xf7b81020 in _PyEval_EvalCodeWithName () from /usr/lib/libpython3.6m.so.1.0
#134 0xf7b821a8 in _PyFunction_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#135 0xf7b82925 in _PyObject_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#136 0xf7b8e07e in _PyObject_Call_Prepend () from /usr/lib/libpython3.6m.so.1.0
#137 0xf7b8e14f in method_call () from /usr/lib/libpython3.6m.so.1.0
#138 0xf7b82d24 in PyObject_Call () from /usr/lib/libpython3.6m.so.1.0
#139 0xf7bf3a47 in slot_tp_init () from /usr/lib/libpython3.6m.so.1.0
#140 0xf7bef6bf in type_call () from /usr/lib/libpython3.6m.so.1.0
#141 0xf7b826db in _PyObject_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#142 0xf7bef55a in _PyObject_FastCallKeywords () from /usr/lib/libpython3.6m.so.1.0
#143 0xf7bfd615 in call_function () from /usr/lib/libpython3.6m.so.1.0
#144 0xf7c2c1e5 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.6m.so.1.0
#145 0xf7bff9b4 in PyEval_EvalCodeEx () from /usr/lib/libpython3.6m.so.1.0
#146 0xf7c008a0 in PyEval_EvalCode () from /usr/lib/libpython3.6m.so.1.0
#147 0xf7c3f34d in builtin_exec () from /usr/lib/libpython3.6m.so.1.0
#148 0xf7bef0ad in _PyCFunction_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#149 0xf7bef49f in _PyCFunction_FastCallKeywords () from /usr/lib/libpython3.6m.so.1.0
#150 0xf7bfd4ad in call_function () from /usr/lib/libpython3.6m.so.1.0
#151 0xf7c2c1e5 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.6m.so.1.0
#152 0xf7b81020 in _PyEval_EvalCodeWithName () from /usr/lib/libpython3.6m.so.1.0
--Type <RET> for more, q to quit, c to continue without paging--
#153 0xf7bb91cf in fast_function () from /usr/lib/libpython3.6m.so.1.0
#154 0xf7bfd57a in call_function () from /usr/lib/libpython3.6m.so.1.0
#155 0xf7c2c1e5 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.6m.so.1.0
#156 0xf7bff9b4 in PyEval_EvalCodeEx () from /usr/lib/libpython3.6m.so.1.0
#157 0xf7c0090e in function_call () from /usr/lib/libpython3.6m.so.1.0
#158 0xf7b82d24 in PyObject_Call () from /usr/lib/libpython3.6m.so.1.0
#159 0xf7ca1f79 in RunModule () from /usr/lib/libpython3.6m.so.1.0
#160 0xf7ca2737 in Py_Main () from /usr/lib/libpython3.6m.so.1.0
#161 0x56556326 in main ()
(gdb)
```

**Comment by hagberg** [comment]
Is this still an issue?   Re-open if so and we'll see if we can troubleshoot more.

**Comment by mcepl** [comment]
Yes, this has been fixed.
