### ISSUE TITLE
GraphML input to GML output fails, node_default not a valid key

### ISSUE THREAD

**Issue by peterjc** [networkx/networkx#3471]
The GraphML primer has an example with node colors encoded as attributes of selected nodes, and weights on edges:

http://graphml.graphdrawing.org/primer/graphml-primer.html#Attributes

Example tested on macOS with Python 3.7 and NetworkX 2.3,

```
$ curl -L -O http://graphml.graphdrawing.org/primer/attributes.graphml
$ python3 --version
Python 3.7.0rc1
$ python3 -c "import networkx as nx; print(nx.__version__)" 
2.3
```

GraphML to GraphML works (mostly, see #3470)

GraphML to GEXF works:

```
$ python3 -c "import networkx as nx; nx.readwrite.gexf.write_gexf(nx.readwrite.graphml.read_graphml('attributes.graphml'), '/dev/stdout')"
<?xml version='1.0' encoding='utf-8'?>
<gexf version="1.2" xmlns="http://www.gexf.net/1.2draft" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/XMLSchema-instance">
  <graph defaultedgetype="undirected" mode="static" name="">
...
```

However, GraphML to GML fails:

```
$ python3 -c "import networkx as nx; nx.readwrite.gml.write_gml(nx.readwrite.graphml.read_graphml('attributes.graphml'), '/dev/stdout')"
graph [
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<decorator-gen-620>", line 2, in write_gml
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/networkx/utils/decorators.py", line 240, in _open_file
    result = func_to_be_decorated(*new_args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/networkx/readwrite/gml.py", line 814, in write_gml
    for line in generate_gml(G, stringizer):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/networkx/readwrite/gml.py", line 718, in generate_gml
    for line in stringize(attr, value, ignored_keys, '  '):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/networkx/readwrite/gml.py", line 658, in stringize
    raise NetworkXError('%r is not a valid key' % (key,))
networkx.exception.NetworkXError: 'node_default' is not a valid key
```

**Comment by peterjc** [comment]
Likewise if you have ``edge_default`` defined, you get a similar exception.

**Comment by dschult** [comment]
I'm not too worried about providing seemless conversion from any graph markup language to any other. If one accepts ```node_default``` as a valid key and the other doesn't it's fine to raise an exception and let the user figure out how they want to change names. 

Perhaps I am missing something here... so feel free to reopen this issue and explain a little more about what is special about node_default and edge_default and how they might be handled in a way that could make this work.
