### ISSUE TITLE
Simrank Similarity ZeroDivisionError

### ISSUE THREAD

**Issue by Dragotic** [networkx/networkx#3524]
I installed the latest development version of networkx from git master branch (2.4rc1.dev) in order to use simrank similarity algorithm that I need for my thesis.
I generate a DiGraph G and when I run 
```python
simrank_similarity(G, source="Source")
```
I have the following error:
```jupyter
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-7-62cdee60c902> in <module>()
----> 1 print(nx.simrank_similarity(G, source="Source"))

~/Desktop/Thesis/thesis/networkx/networkx/algorithms/similarity.py in simrank_similarity(G, source, target, importance_factor, max_iterations, tolerance)
   1149         prevsim = newsim
   1150         newsim = {u: {v: sim(u, v) if u is not v else 1
-> 1151                       for v in newsim[u]} for u in newsim}
   1152 
   1153     if source is not None and target is not None:

~/Desktop/Thesis/thesis/networkx/networkx/algorithms/similarity.py in <dictcomp>(.0)
   1149         prevsim = newsim
   1150         newsim = {u: {v: sim(u, v) if u is not v else 1
-> 1151                       for v in newsim[u]} for u in newsim}
   1152 
   1153     if source is not None and target is not None:

~/Desktop/Thesis/thesis/networkx/networkx/algorithms/similarity.py in <dictcomp>(.0)
   1149         prevsim = newsim
   1150         newsim = {u: {v: sim(u, v) if u is not v else 1
-> 1151                       for v in newsim[u]} for u in newsim}
   1152 
   1153     if source is not None and target is not None:

~/Desktop/Thesis/thesis/networkx/networkx/algorithms/similarity.py in <lambda>(u, v)
   1142     # `u` and `v` with respect to the previous similarity values.
   1143     avg_sim = lambda s: sum(newsim[w][x] for (w, x) in s) / len(s)
-> 1144     sim = lambda u, v: importance_factor * avg_sim(list(product(G[u], G[v])))
   1145 
   1146     for _ in range(max_iterations):

~/Desktop/Thesis/thesis/networkx/networkx/algorithms/similarity.py in <lambda>(s)
   1141     # These functions compute the update to the similarity value of the nodes
   1142     # `u` and `v` with respect to the previous similarity values.
-> 1143     avg_sim = lambda s: sum(newsim[w][x] for (w, x) in s) / len(s)
   1144     sim = lambda u, v: importance_factor * avg_sim(list(product(G[u], G[v])))
   1145 

ZeroDivisionError: division by zero
```
Any idea why this is happening? 

Thank you in advance

**Comment by dschult** [comment]
A quick look at the error log suggests that ```s``` has length zero, probs because G[u] and G[v] have length zero. Do you have isolated nodes? maybe they have no neighbors? I haven't looked at the code to see what happens when there are isolated nodes. I've only looked at your error message.

**Comment by Dragotic** [comment]
Well, I'm doing a pre-process on the graph before using simrank on it.
I'm removing the isolated nodes using:
```python
G.remove_nodes_from(list(nx.isolates(G)))
```
But it stills throws the ZeroDivisionError

**Comment by Pascal-Ortiz** [comment]
I suppose that your graph is a directed one. In this case, `isolates(G)` are vertices with no in-neighbors **and** no out-neighbors. This is not what you need. In your case, you need to remove the **sources** of the graph ie vertices with no predecessor because the function divides by `len(in_neighbors_u) * len(in_neighbors_v)`.

**Comment by Dragotic** [comment]
I created a function that checks if there are nodes with no predecessors. 

Still getting the ZerroDivisonError

**Comment by Pascal-Ortiz** [comment]
> I created a function that checks if there are nodes with no predecessors.

And you remove them from the graph?

> 
> Still getting the ZeroDivisonError

Could you provide a [minimal working example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by Pascal-Ortiz** [comment]
> I created a function that checks if there are nodes with no predecessors.
> 
> Still getting the ZeroDivisonError

Perhaps because removing sources create another source.

Here is a minimal example:

```python
from itertools import product
import networkx as nx
from numpy import array




def _is_close(d1, d2, atolerance=0, rtolerance=0):
    """Determines whether two adjacency matrices are within
    a provided tolerance.
    
    Parameters
    ----------
    d1 : dict
        Adjacency dictionary
    
    d2 : dict
        Adjacency dictionary
    
    atolerance : float
        Some scalar tolerance value to determine closeness
    
    rtolerance : float
        A scalar tolerance value that will be some proportion
        of ``d2``'s value
    
    Returns
    -------
    closeness : bool
        If all of the nodes within ``d1`` and ``d2`` are within
        a predefined tolerance, they are considered "close" and
        this method will return True. Otherwise, this method will
        return False.
    
    """
    # Pre-condition: d1 and d2 have the same keys at each level if they
    # are dictionaries.
    if not isinstance(d1, dict) and not isinstance(d2, dict):
        return abs(d1 - d2) <= atolerance + rtolerance * abs(d2)
    return all(all(_is_close(d1[u][v], d2[u][v]) for v in d1[u]) for u in d1)

def simrank_similarity(G, source=None, target=None, importance_factor=0.9,
                       max_iterations=100, tolerance=1e-4):
    """Returns the SimRank similarity of nodes in the graph ``G``.

    SimRank is a similarity metric that says "two objects are considered
    to be similar if they are referenced by similar objects." [1]_.
    
    The pseudo-code definition from the paper is:

        def simrank(G, u, v):
            in_neighbors_u = G.predecessors(u)
            in_neighbors_v = G.predecessors(v)
            scale = C / (len(in_neighbors_u) * len(in_neighbors_v))
            return scale * sum(simrank(G, w, x)
                               for w, x in product(in_neighbors_u,
                                                   in_neighbors_v))
    
    where ``G`` is the graph, ``u`` is the source, ``v`` is the target,
    and ``C`` is a float decay or importance factor between 0 and 1.
    
    The SimRank algorithm for determining node similarity is defined in
    [2]_.

    Parameters
    ----------
    G : NetworkX graph
        A NetworkX graph

    source : node
        If this is specified, the returned dictionary maps each node
        ``v`` in the graph to the similarity between ``source`` and
        ``v``.

    target : node
        If both ``source`` and ``target`` are specified, the similarity
        value between ``source`` and ``target`` is returned. If
        ``target`` is specified but ``source`` is not, this argument is
        ignored.

    importance_factor : float
        The relative importance of indirect neighbors with respect to
        direct neighbors.

    max_iterations : integer
        Maximum number of iterations.

    tolerance : float
        Error tolerance used to check convergence. When an iteration of
        the algorithm finds that no similarity value changes more than
        this amount, the algorithm halts.

    Returns
    -------
    similarity : dictionary or float
        If ``source`` and ``target`` are both ``None``, this returns a
        dictionary of dictionaries, where keys are node pairs and value
        are similarity of the pair of nodes.

        If ``source`` is not ``None`` but ``target`` is, this returns a
        dictionary mapping node to the similarity of ``source`` and that
        node.

        If neither ``source`` nor ``target`` is ``None``, this returns
        the similarity value for the given pair of nodes.

    Examples
    --------
    If the nodes of the graph are numbered from zero to *n - 1*, where *n*
    is the number of nodes in the graph, you can create a SimRank matrix
    from the return value of this function where the node numbers are
    the row and column indices of the matrix::

        >>> import networkx as nx
        >>> from numpy import array
        >>> G = nx.cycle_graph(4)
        >>> sim = nx.simrank_similarity(G)
        >>> lol = [[sim[u][v] for v in sorted(sim[u])] for u in sorted(sim)]
        >>> sim_array = array(lol)

    References
    ----------
    .. [1] https://en.wikipedia.org/wiki/SimRank
    .. [2] G. Jeh and J. Widom.
           "SimRank: a measure of structural-context similarity",
           In KDD'02: Proceedings of the Eighth ACM SIGKDD
           International Conference on Knowledge Discovery and Data Mining,
           pp. 538--543. ACM Press, 2002.
    """
    prevsim = None

    # build up our similarity adjacency dictionary output
    newsim = {u: {v: 1 if u == v else 0 for v in G} for u in G}

    # These functions compute the update to the similarity value of the nodes
    # `u` and `v` with respect to the previous similarity values.
    avg_sim = lambda s: sum(newsim[w][x] for (w, x) in s) / len(s)
    sim = lambda u, v: importance_factor * avg_sim(list(product(G[u], G[v])))

    for _ in range(max_iterations):
        if prevsim and _is_close(prevsim, newsim, tolerance):
            break
        prevsim = newsim
        newsim = {u: {v: sim(u, v) if u is not v else 1
                      for v in newsim[u]} for u in newsim}

    if source is not None and target is not None:
        return newsim[source][target]
    if source is not None:
        return newsim[source]
    return newsim


G = nx.DiGraph()

edges=[("A", "B"), ("B", "C")]
G.add_edges_from(edges)
in_degrees=G.in_degree(G.nodes())
print(in_degrees)

sim = simrank_similarity(G)

print(sim)
```

outputting:

```
[('A', 0), ('B', 1), ('C', 1)]
Traceback (most recent call last):
  File "sim.py", line 161, in <module>
    sim = simrank_similarity(G)
  File "sim.py", line 145, in simrank_similarity
    for v in newsim[u]} for u in newsim}
  File "sim.py", line 145, in <dictcomp>
    for v in newsim[u]} for u in newsim}
  File "sim.py", line 145, in <dictcomp>
    for v in newsim[u]} for u in newsim}
  File "sim.py", line 138, in <lambda>
    sim = lambda u, v: importance_factor * avg_sim(list(product(G[u], G[v])))
  File "sim.py", line 137, in <lambda>
    avg_sim = lambda s: sum(newsim[w][x] for (w, x) in s) / len(s)
ZeroDivisionError: division by zero

```

**Comment by Dragotic** [comment]
I get that and thanks for helping me out with this example. I will check it again in more detail.

However, I really don't get it how a function that simply states "provide me these inputs aka the Graph G and the source, target nodes" and I will give you an output throws an error that has nothing to do with my input but rather does not handle the case where a graph might have nodes with different properties ie. no in edges. But I get it, it's still under development and not on a stable version.

**Comment by dschult** [comment]
Thanks @Pascal-Ortiz for the minimal example. That helps a lot with debugging. And this does look like a "Bug". As @Dragotic points out it should be able to handle this case. That said, the fact that this is not yet a stable release doesn't have much to do with whether there are bugs.  Bugs exist in all software. The correct approach is not to trust any software. Test it. We do as best as we can to eliminate bugs, but they show up anyway.

It seems like this one should be fairly straightforward to track down and fix. We need a PR for it.
Thanks for reporting the bug! We might be able to find a work-around before a fix too...
Any help is appreciated.

**Comment by Dragotic** [comment]
Quoting from [SimRank - Wikipedia](https://en.wikipedia.org/wiki/SimRank#Basic_SimRank_equation)

> A slight technicality here is that either a or b may not have any in-neighbors. Since there is no way to infer any similarity between a and b in this case, similarity is set to s(a,b)=0, so the summation in the above equation is defined to be 0 when I(a)=\emptyset  or I(b)=\emptyset

and the code from simrank networkx implementation
```python
    avg_sim = lambda s: sum(newsim[w][x] for (w, x) in s) / len(s)
    sim = lambda u, v: importance_factor * avg_sim(list(product(G[u], G[v])))
```

checking if `len(s) == 0` and setting `avg_sim = 0` will solve this problem, right?

**Comment by dschult** [comment]
Excellent!  Thanks for finding this and that is a good fix. :)
