### ISSUE TITLE
write_gexf crashes when node-attributes are list

### ISSUE THREAD

**Issue by EmilBode** [networkx/networkx#3572]
**Problem**
When making a grah where (some) attributes are lists, write_gexf crashes, without a good explanation.

**Reproducible example**
```
import networkx as nx
G=nx.Graph()
G.add_node('MyNode', myattr=['Att1','Att2'])
nx.write_gexf(G, 'C:\\Users\\Emil\\Desktop\\temp.gexf')
```
This gives me:
```
Traceback (most recent call last):

  File "<ipython-input-1-f3eb8f049e9d>", line 4, in <module>
    nx.write_gexf(G, 'C:\\Users\\Emil\\Desktop\\temp.gexf')

  File "<C:\ProgramData\Anaconda3\lib\site-packages\decorator.py:decorator-gen-756>", line 2, in write_gexf

  File "C:\ProgramData\Anaconda3\lib\site-packages\networkx\utils\decorators.py", line 240, in _open_file
    result = func_to_be_decorated(*new_args, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\networkx\readwrite\gexf.py", line 88, in write_gexf
    writer.add_graph(G)

  File "C:\ProgramData\Anaconda3\lib\site-packages\networkx\readwrite\gexf.py", line 315, in add_graph
    self.add_nodes(G, graph_element)

  File "C:\ProgramData\Anaconda3\lib\site-packages\networkx\readwrite\gexf.py", line 362, in add_nodes
    node_data, default)

  File "C:\ProgramData\Anaconda3\lib\site-packages\networkx\readwrite\gexf.py", line 445, in add_attributes
    for val, start, end in v:

ValueError: too many values to unpack (expected 3)
```
The actual cause seems to be line 443 in `gexf.py` (2 lines up), where `if isinstance(v, list)` treats lists different, probably expecting some specific kind of data there. Maybe the check for *dynamic data* needs to be more extensive?

I'm not sure if this is fully fixable (I don't even know if multi-valued attributes are even allowed in `.gexf`-files), but a more informative error message would be nice.

**System details**
System: WIndows 10, 64-bit
Python: 3.7.3 (64-bit) (also on 3.7.1/64)
Run from Spyder, version 3.3.4 (also on 3.3.2)
Networkx version: 2.3 (also on 2.1 and 2.2)

**Comment by dschult** [comment]
I agree that this is confusing. I'm not actually sure of the history of this "dynamic" implementation were we assume list attributes signify "dynamic" information.   Perhaps it would be better to require a graph attribute called "mode" be set to "dynamic" before the code parsing list attributes.

Short term fix: get a better error message when attributes that are lists don't fit the structure of dynamic data. 
Long term fix: allow attributes with lists as values even for static graphs.
