### ISSUE TITLE
LPA algorithm may have some problems with the directed graph and weights.

### ISSUE THREAD

**Issue by wsp50317** [networkx/networkx#3616]
LPA algorithm can work with the directed graph in the developed version. (Maybe it's solved by #3545)
But it seems that it has some problems when the input is a directed graph with weights.
Below is a simple program and the output:

Program:
```
import networkx as nx
import matplotlib.pyplot as plt
from networkx.algorithms import community

DG = nx.DiGraph()
DG.add_weighted_edges_from([(1, 2, 0.5), (3, 1, 0.75)])
communities_generator = list(community.asyn_lpa_communities(DG, weight = 'weight'))
nx.draw(DG, with_labels=True, font_weight='bold')
plt.show()
```

Output:
```
Traceback (most recent call last):
  File "/home/wu/PerformanceAnalysis/Perf/Ros/Label_progation/test/test.py", line 21, in <module>
    communities_generator = list(community.asyn_lpa_communities(DG, weight = 'weight'))
  File "</usr/local/lib/python3.5/dist-packages/decorator.py:decorator-gen-508>", line 2, in asyn_lpa_communities
  File "/home/wu/networkx/networkx/utils/decorators.py", line 464, in _random_state
    return func(*new_args, **kwargs)
  File "/home/wu/networkx/networkx/algorithms/community/label_propagation.py", line 88, in asyn_lpa_communities
    if weight else 1})
  File "/home/wu/networkx/networkx/classes/reportviews.py", line 930, in __getitem__
    return self._adjdict[u][v]
KeyError: 1

```

**Comment by wsp50317** [comment]
I have found the problem. The nodes in line 87 is opposite in label_propagation.py.
I have submitted the pull request about this issue.

**Comment by dschult** [comment]
Excellent!  Thanks so Much!!
