### ISSUE TITLE
[BUG] Inappropriate `out_edge` return when node type is str

### ISSUE THREAD

**Issue by hanayashiki** [networkx/networkx#3653]
If you use `int` as the node type, and apply `G.out_edges` to a nonexisting node, it throws an exception (perhaps because the input is understood as `nbunch`)
```
G = nx.DiGraph()
G.add_edge(1, 2)
G.out_edges(1)
Out[9]: OutEdgeDataView([(1, 2)])
G.out_edges(3)
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\networkx\classes\graph.py", line 1908, in bunch_iter
    for n in nlist:
TypeError: 'int' object is not iterable
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-1253e8a219cb>", line 1, in <module>
    G.out_edges(3)
  File "D:\Anaconda3\lib\site-packages\networkx\classes\reportviews.py", line 936, in __call__
    return self.dataview(self, nbunch, data, default)
  File "D:\Anaconda3\lib\site-packages\networkx\classes\reportviews.py", line 648, in __init__
    nbunch = list(viewer._graph.nbunch_iter(nbunch))
  File "D:\Anaconda3\lib\site-packages\networkx\classes\graph.py", line 1916, in bunch_iter
    raise NetworkXError(msg)
networkx.exception.NetworkXError: nbunch is not a node or a sequence of nodes.
```
But when the type is `str`, you get nothing but an empty edge view. This is probably because `str` is iterable but `int` is not.
I think these inconsistent behaviors makes users prone to bugs.

**Comment by hanayashiki** [comment]
I think the basic problem is that some element types are also `container`. This is a weakness from the API design.
Although inperfect, I think `NodeNotFound` is a good idea.

**Comment by dschult** [comment]
I think if we make the existing API can be used in a more restrictive way to do as you say:
- Use G.succ[u] to get edges (actually neighbors, but you can make edges) of a particular node u
- Use G.out_edges(container) to get edges from any of a container of nodes.

You can treat the API that way now. But it is not enforced.
