### ISSUE TITLE
Dictionary Changed Size during iteration

### ISSUE THREAD

**Issue by JulianSchmidtke** [networkx/networkx#3878]
Hello,

I want to Cluster a big weighted, directed DOT-Graph (9000 nodes with 90000 Edges) with the girvan_newman alg.

i have the following code:

```
import networkx as nx
from networkx.algorithms import community

G = nx.drawing.nx_pydot.read_dot('./graph.dot')

communities_generator = community.girvan_newman(G)
top_level_communities = next(communities_generator)
next_level_communities = next(communities_generator)
```

when i run the Code i get the following error:
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\Julian\.vscode\extensions\ms-python.python-2020.3.69010\pythonFiles\lib\python\debugpy\no_wheels\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\Julian\.vscode\extensions\ms-python.python-2020.3.69010\pythonFiles\lib\python\debugpy\no_wheels\debugpy/..\debugpy\server\cli.py", line 427, in main
    run()
  File "c:\Users\Julian\.vscode\extensions\ms-python.python-2020.3.69010\pythonFiles\lib\python\debugpy\no_wheels\debugpy/..\debugpy\server\cli.py", line 264, in run_file
    runpy.run_path(options.target, run_name="__main__")
  File "C:\Program Files (x86)\Python38-32\lib\runpy.py", line 263, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Program Files (x86)\Python38-32\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Program Files (x86)\Python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Repositories\pyCommunities\community.py", line 7, in <module>
    top_level_communities = next(communities_generator)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\networkx\algorithms\community\centrality.py", line 152, in girvan_newman
    g.remove_edges_from(nx.selfloop_edges(g))
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\networkx\classes\multigraph.py", line 646, in remove_edges_from
    for e in ebunch:
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\networkx\classes\function.py", line 1165, in <genexpr>
    if n in nbrs for d in nbrs[n].values())
  File "C:\Program Files (x86)\Python38-32\lib\_collections_abc.py", line 761, in __iter__
    for key in self._mapping:
RuntimeError: dictionary changed size during iteration
```

In the multigraph.py / function.py files i do not find a loop that deletes content in a dictionary so i don't know what to do. 

Python 3.8.2
Newest networkx version

**Comment by JulianSchmidtke** [comment]
I got the issue.
I had an node that referenced itself.
