### ISSUE TITLE
Test failure: spectral_graph_forge() missing 2 required positional arguments

### ISSUE THREAD

**Issue by PureTryOut** [networkx/networkx#3942]
Running Python 3.8 on Alpine Linux (planning to put networkx in the repos):

```
Traceback (most recent call last):
  File "setup.py", line 145, in <module>
    setup(
  File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.8/site-packages/setuptools/command/test.py", line 238, in run
    self.run_tests()
  File "/usr/lib/python3.8/site-packages/setuptools/command/test.py", line 256, in run_tests
    test = unittest.main(
  File "/usr/lib/python3.8/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.8/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib/python3.8/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/usr/lib/python3.8/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib/python3.8/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib/python3.8/unittest/loader.py", line 405, in _find_tests
    tests, should_recurse = self._find_test_path(
  File "/usr/lib/python3.8/unittest/loader.py", line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/usr/lib/python3.8/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.8/unittest/loader.py", line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python3.8/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.8/unittest/loader.py", line 205, in loadTestsFromName
    test = obj()
TypeError: spectral_graph_forge() missing 2 required positional arguments: 'G' and 'alpha'
```

**Comment by MridulS** [comment]
Is there a Dockerfile to reproduce this? I'm stuck on installing scipy (required for spectral_graph_forge test) with the image alpine python image (3.11 and py3.8) `python:3.8-alpine` https://hub.docker.com/_/python

**Comment by dschult** [comment]
Any more info on how to recreate this problem?
Please comment again or reopen the issue.

**Comment by PureTryOut** [comment]
Uh, well should be easy with an Alpine install or Docker.

```
apk add py3-decorator py3-setuptools py3-pytest py3-pygraphviz py3-pydot py3-numpy py3-scipy py3-yaml py3-pandas py3-matplotlib py3-lxml
python3 setup.py test
```

**Comment by jarrodmillman** [comment]
We don't support ``python3 setup.py test``.  If you want to run the tests, please see:
  https://networkx.github.io/documentation/latest/install.html#testing

**Comment by PureTryOut** [comment]
Ah, pytest, of course, I should've known. Thanks, that works!
