### ISSUE TITLE
Issues with write_dot

### ISSUE THREAD

**Issue by hcars** [networkx/networkx#4172]
When I run the following: 
```
G = nx.barabasi_albert_graph(3, 2)
nx.nx_agraph.write_dot(G, 'test.dot')
```
I get this error:
```
Traceback (most recent call last):
  File "/home/hlc5v/.conda/envs/network_crawler/lib/python3.7/site-packages/pygraphviz/agraph.py", line 665, in out_edges_iter
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hlc5v/.conda/envs/network_crawler/lib/python3.7/site-packages/networkx/drawing/nx_agraph.py", line 194, in write_dot
    A.clear()
  File "/home/hlc5v/.conda/envs/network_crawler/lib/python3.7/site-packages/pygraphviz/agraph.py", line 951, in clear
    self.remove_edges_from(self.edges())
  File "/home/hlc5v/.conda/envs/network_crawler/lib/python3.7/site-packages/pygraphviz/agraph.py", line 573, in edges
    return list(self.edges_iter(nbunch=nbunch, keys=keys))
  File "/home/hlc5v/.conda/envs/network_crawler/lib/python3.7/site-packages/pygraphviz/agraph.py", line 734, in edges_iter
    for e in self.out_edges_iter(keys=keys):
RuntimeError: generator raised StopIteration
```

**Comment by jarrodmillman** [comment]
Hmm, that works for me with graphviz 2.42 and pygraphviz 1.6.  What version of pygraphviz and graphviz are you using?

**Comment by hcars** [comment]
@jarrodmillman Thank you! It appears that the pygraphviz available through conda installs is outdated. I was using pygraphviz 1.6.
