### ISSUE TITLE
broken in python 3.9

### ISSUE THREAD

**Issue by jerry153fish** [networkx/networkx#4335]
Python version `Python 3.9.0` 

How to reproduce 

1. `pip install networkx`

```
>>> import networkx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jerry/Projects/btc/cloudformation-v2/env/lib/python3.9/site-packages/networkx/__init__.py", line 114, in <module>
    import networkx.generators
  File "/Users/jerry/Projects/btc/cloudformation-v2/env/lib/python3.9/site-packages/networkx/generators/__init__.py", line 14, in <module>
    from networkx.generators.intersection import *
  File "/Users/jerry/Projects/btc/cloudformation-v2/env/lib/python3.9/site-packages/networkx/generators/intersection.py", line 13, in <module>
    from networkx.algorithms import bipartite
  File "/Users/jerry/Projects/btc/cloudformation-v2/env/lib/python3.9/site-packages/networkx/algorithms/__init__.py", line 16, in <module>
    from networkx.algorithms.dag import *
  File "/Users/jerry/Projects/btc/cloudformation-v2/env/lib/python3.9/site-packages/networkx/algorithms/dag.py", line 23, in <module>
    from fractions import gcd
ImportError: cannot import name 'gcd' from 'fractions' (/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/fractions.py)
```
Need to replace gcd with match.gcd

**Comment by jerry153fish** [comment]
Sorry seem to be fixed in the code
