### ISSUE TITLE
Problem with read/write_gml with nan/inf attributes

### ISSUE THREAD

**Issue by jml-happy** [networkx/networkx#4484]
If a node or edge attribute is nan or inf then nx.write_gml() writes these as NAN and INF respectively, but they are unquoted.
As a result reading the gml file back in raises an exception since they match the key regex in tokenize().

Is this intentional? 

Writing a de/stringizer doesn't seem to work (though honestly I've never tried to write a de/stringizer before so maybe I'm doing it wrong).

A workaround is to iterate over the attributes and change to a string/float before/after writing/reading.   A hacky fix is to put special handling in gml.py.  It would be nice if NetworkX had some way to handle this.

**To reproduce:**
Python 3.7
NetworkX 2.5
numpy 1.19.4
conda environment
```
>>> import networkx as nx
>>> import numpy as np
>>> 
>>> nx.__version__
'2.5'
>>> np.__version__
'1.19.4'
>>> 
>>> G_nde = nx.path_graph(3)
>>> for n in G_nde.nodes:
...     G_nde.nodes[n]["nandata"] = np.nan
...     G_nde.nodes[n]["infdata"] = np.inf
... 
>>> G_edg = nx.path_graph(3)
>>> for u, v in G_edg.edges:
...     G_edg[u][v]["nandata"] = np.nan
...     G_edg[u][v]["infdata"] = np.inf
... 
>>> G_nde.nodes(data=True)
NodeDataView({0: {'nandata': nan, 'infdata': inf}, 1: {'nandata': nan, 'infdata': inf}, 2: {'nandata': nan, 'infdata': inf}})
>>> G_edg.edges(data=True)
EdgeDataView([(0, 1, {'nandata': nan, 'infdata': inf}), (1, 2, {'nandata': nan, 'infdata': inf})])
>>> 
>>> nx.write_gml(G_nde, "test_naninf_nodes.gml")
>>> nx.write_gml(G_edg, "test_naninf_edges.gml")
>>> 
>>> 
>>> H_nde = nx.read_gml("test_naninf_nodes.gml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<decorator-gen-684>", line 2, in read_gml
  File "/home/USERNAME/anaconda3/envs/CONDA_ENV_NAME/lib/python3.7/site-packages/networkx/utils/decorators.py", line 239, in _open_file
    result = func_to_be_decorated(*new_args, **kwargs)
  File "/home/USERNAME/anaconda3/envs/CONDA_ENV_NAME/lib/python3.7/site-packages/networkx/readwrite/gml.py", line 181, in read_gml
    G = parse_gml_lines(filter_lines(path), label, destringizer)
  File "/home/USERNAME/anaconda3/envs/CONDA_ENV_NAME/lib/python3.7/site-packages/networkx/readwrite/gml.py", line 411, in parse_gml_lines
    graph = parse_graph()
  File "/home/USERNAME/anaconda3/envs/CONDA_ENV_NAME/lib/python3.7/site-packages/networkx/readwrite/gml.py", line 400, in parse_graph
    curr_token, dct = parse_kv(next(tokens))
  File "/home/USERNAME/anaconda3/envs/CONDA_ENV_NAME/lib/python3.7/site-packages/networkx/readwrite/gml.py", line 355, in parse_kv
    curr_token, value = parse_dict(curr_token)
  File "/home/USERNAME/anaconda3/envs/CONDA_ENV_NAME/lib/python3.7/site-packages/networkx/readwrite/gml.py", line 394, in parse_dict
    curr_token, dct = parse_kv(curr_token)
  File "/home/USERNAME/anaconda3/envs/CONDA_ENV_NAME/lib/python3.7/site-packages/networkx/readwrite/gml.py", line 355, in parse_kv
    curr_token, value = parse_dict(curr_token)
  File "/home/USERNAME/anaconda3/envs/CONDA_ENV_NAME/lib/python3.7/site-packages/networkx/readwrite/gml.py", line 394, in parse_dict
    curr_token, dct = parse_kv(curr_token)
  File "/home/USERNAME/anaconda3/envs/CONDA_ENV_NAME/lib/python3.7/site-packages/networkx/readwrite/gml.py", line 375, in parse_kv
    unexpected(curr_token, "an int, float, string or '['")
  File "/home/USERNAME/anaconda3/envs/CONDA_ENV_NAME/lib/python3.7/site-packages/networkx/readwrite/gml.py", line 330, in unexpected
    raise NetworkXError(f"expected {expected}, found {value} at ({lineno}, {pos})")
networkx.exception.NetworkXError: expected an int, float, string or '[', found 'NAN' at (5, 13)
>>> 
>>> 
>>> 
>>> H_edg = nx.read_gml("test_naninf_edges.gml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<decorator-gen-684>", line 2, in read_gml
  File "/home/USERNAME/anaconda3/envs/CONDA_ENV_NAME/lib/python3.7/site-packages/networkx/utils/decorators.py", line 239, in _open_file
    result = func_to_be_decorated(*new_args, **kwargs)
  File "/home/USERNAME/anaconda3/envs/CONDA_ENV_NAME/lib/python3.7/site-packages/networkx/readwrite/gml.py", line 181, in read_gml
    G = parse_gml_lines(filter_lines(path), label, destringizer)
  File "/home/USERNAME/anaconda3/envs/CONDA_ENV_NAME/lib/python3.7/site-packages/networkx/readwrite/gml.py", line 411, in parse_gml_lines
    graph = parse_graph()
  File "/home/USERNAME/anaconda3/envs/CONDA_ENV_NAME/lib/python3.7/site-packages/networkx/readwrite/gml.py", line 400, in parse_graph
    curr_token, dct = parse_kv(next(tokens))
  File "/home/USERNAME/anaconda3/envs/CONDA_ENV_NAME/lib/python3.7/site-packages/networkx/readwrite/gml.py", line 355, in parse_kv
    curr_token, value = parse_dict(curr_token)
  File "/home/USERNAME/anaconda3/envs/CONDA_ENV_NAME/lib/python3.7/site-packages/networkx/readwrite/gml.py", line 394, in parse_dict
    curr_token, dct = parse_kv(curr_token)
  File "/home/USERNAME/anaconda3/envs/CONDA_ENV_NAME/lib/python3.7/site-packages/networkx/readwrite/gml.py", line 355, in parse_kv
    curr_token, value = parse_dict(curr_token)
  File "/home/USERNAME/anaconda3/envs/CONDA_ENV_NAME/lib/python3.7/site-packages/networkx/readwrite/gml.py", line 394, in parse_dict
    curr_token, dct = parse_kv(curr_token)
  File "/home/USERNAME/anaconda3/envs/CONDA_ENV_NAME/lib/python3.7/site-packages/networkx/readwrite/gml.py", line 375, in parse_kv
    unexpected(curr_token, "an int, float, string or '['")
  File "/home/USERNAME/anaconda3/envs/CONDA_ENV_NAME/lib/python3.7/site-packages/networkx/readwrite/gml.py", line 330, in unexpected
    raise NetworkXError(f"expected {expected}, found {value} at ({lineno}, {pos})")
networkx.exception.NetworkXError: expected an int, float, string or '[', found 'NAN' at (17, 13)
>>> 
```
**Workaround for nodes**
```
>>> I_nde = G_nde.copy()
>>> 
>>> I_nde.nodes(data=True)
NodeDataView({0: {'nandata': nan, 'infdata': inf}, 1: {'nandata': nan, 'infdata': inf}, 2: {'nandata': nan, 'infdata': inf}})
>>> 
>>> for n, d in I_nde.nodes(data=True):
...     for k, v in d.items():
...             if isinstance(v, float):
...                     if np.isnan(v):
...                             I_nde.nodes[n][k] = "NAN"
...                     if np.isinf(v):
...                             I_nde.nodes[n][k] = "INF"
... 
>>> 
>>> nx.write_gml(I_nde, "test_naninf_nodes_string.gml")
>>> 
>>> J_nde = nx.read_gml("test_naninf_nodes_string.gml")
>>> J_nde.nodes(data=True)
NodeDataView({'0': {'nandata': 'NAN', 'infdata': 'INF'}, '1': {'nandata': 'NAN', 'infdata': 'INF'}, '2': {'nandata': 'NAN', 'infdata': 'INF'}})
>>> 
>>> for n, d in J_nde.nodes(data=True):
...     for k, v in d.items():
...             if isinstance(v, str):
...                     if v == "NAN":
...                             J_nde.nodes[n][k] = np.nan
...                     if v == "INF":
...                             J_nde.nodes[n][k] = np.inf
... 
>>> 
>>> J_nde.nodes(data=True)
NodeDataView({'0': {'nandata': nan, 'infdata': inf}, '1': {'nandata': nan, 'infdata': inf}, '2': {'nandata': nan, 'infdata': inf}})
>>> 
```

**Hacky fix:**
Add
```
if value in {"NAN", "INF", "-INF"}:
     value = float(value)
     i = 1
```
after line 313 of gml.py

**Comment by rossbar** [comment]
`np.nan` and `np.inf` are valid floats: `isinstance(np.nan, float) -> True` which sends the parser down the float branch here:

https://github.com/networkx/networkx/blob/6acdc535f885978a0729355833472abda82266f5/networkx/readwrite/gml.py#L681-L692

Note that there is no special casing in that branch to handle valid float instances that aren't numbers. Something *could* be added there, but my initial reaction is that would be brittle because of things like `float(nan) != np.nan`.

Unfortunately, the fact that these values are valid floats also means the `stringizer` branch is never hit, so defining a custom stringizer won't help you in this case.

Ideally NX's gml functionality should do whatever the GML standard says. I'm not familiar with the format and couldn't find any standards document with a quick web search. The links in our own docs don't seem to point to one either (something to update). If anyone knows of the location of a GML standards doc and can share here I'd appreciate it!

**Comment by jml-happy** [comment]
I've uploaded a copy of [Himsolt's *GML: A portable Graph File Format* here](https://github.com/jml-happy/documents/blob/main/gml-technical-report.pdf).  I think this is the only version, but there may be a newer version out there.  

The standard makes no mention of nan or infinite values.  Looking at the BNF, NetworkX's output for nan and positive infinity are in the sub-language for key's (since repr(value).upper() is used).  NetworkX's tokenize() does match NAN and INF for keys, but rejects them for values since they match keys. -INF is not in the GML language and doesn't match any tokenize() regex.  This is the same for python native and numpy nan and infinities.

I think outputting inf as +INF and nan as _NAN is a decent solution.  Since _ isn't in the GML alphabet NAN and INF would remain valid keys and the _ prefix could be used for any future special cases.  But it does extend the alphabet beyond the standard.

Doing comparison with the string representation avoids the problem of float(nan) != np.nan.  Alternatively, np.isnan(), np.isneginf(), and np.isposinf() could be used (works with both python native and numpy values), but then gml.py would have to import numpy. I don't know which is preferred.  I didn't include anything to handle pandas pd.NA since I think there's a meaningful difference between NA/missing values in general, and nan floats.

I've created a [pull request](https://github.com/networkx/networkx/pull/4497) and sent this to the mailing list.

------------

### Current behavior
```
>>> import networkx as nx
>>> nx.__version__
'2.6rc1.dev_20201228174925'
>>> import numpy as np
>>> np.__version__
'1.19.4'
>>> 
>>> special_floats = [float('nan'), float('+inf'), float('-inf'),  np.nan, np.inf, np.inf * -1]
>>> 
>>> G = nx.cycle_graph(6)
>>> 
>>> # Assign special floats to attributes of G
>>> for i, e in enumerate(G.nodes):
...     G.nodes[i]["ndefloat"] = special_floats[i]
... 
>>> # Show the resulting assignments
>>> G.nodes(data=True)
NodeDataView({0: {'ndefloat': nan}, 1: {'ndefloat': inf}, 2: {'ndefloat': -inf}, 3: {'ndefloat': nan}, 4: {'ndefloat': inf}, 5: {'ndefloat': -inf}})
>>> 
>>> # Write gml file
>>> nx.write_gml(G, "special_floats.as.attributes.gml")
### ERROR ###
```

Contents of special_floats.as.attributes.gml:
```
graph [
  node [
    id 0
    label "0"
    ndefloat NAN
  ]
  node [
    id 1
    label "1"
    ndefloat INF
  ]
  node [
    id 2
    label "2"
    ndefloat -INF
  ]
  node [
    id 3
    label "3"
    ndefloat NAN
  ]
  node [
    id 4
    label "4"
    ndefloat INF
  ]
  node [
    id 5
    label "5"
    ndefloat -INF
  ]
  edge [
    source 0
    target 1
  ]
  edge [
    source 0
    target 5
  ]
  edge [
    source 1
    target 2
  ]
  edge [
    source 2
    target 3
  ]
  edge [
    source 3
    target 4
  ]
  edge [
    source 4
    target 5
  ]
]
```

### After this pull request

Contents of special_floats.as.attributes.gml:
```
graph [
  node [
    id 0
    label "0"
    ndefloat _NAN
  ]
  node [
    id 1
    label "1"
    ndefloat +INF
  ]
  node [
    id 2
    label "2"
    ndefloat -INF
  ]
  node [
    id 3
    label "3"
    ndefloat _NAN
  ]
  node [
    id 4
    label "4"
    ndefloat +INF
  ]
  node [
    id 5
    label "5"
    ndefloat -INF
  ]
  edge [
    source 0
    target 1
  ]
  edge [
    source 0
    target 5
  ]
  edge [
    source 1
    target 2
  ]
  edge [
    source 2
    target 3
  ]
  edge [
    source 3
    target 4
  ]
  edge [
    source 4
    target 5
  ]
]
```
GML file can be read successfully:
```
>>> H = nx.read_gml("special_floats.as.attributes.gml")
>>> H.nodes(data=True)
NodeDataView({'0': {'ndefloat': nan}, '1': {'ndefloat': inf}, '2': {'ndefloat': -inf}, '3': {'ndefloat': nan}, '4': {'ndefloat': inf}, '5': {'ndefloat': -inf}})
>>> 
```

Also checked that including NAN and INF in other floats won't be read as valid.
