### ISSUE TITLE
Networkx fails to be installed with Python 3.9 and PIP 20.2.1

### ISSUE THREAD

**Issue by ITAYC0HEN** [networkx/networkx#4503]
Hey, when trying to install networkx on Arch Linux (64bit) with PIP, the following errors are received:

```
$ sudo pip install networkx

Collecting networkx
  Downloading networkx-2.5-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 729 kB/s 
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 216, in _main
    status = self.run(options, args)
  File "/usr/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 324, in run
    requirement_set = resolver.resolve(
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 331, in _get_abstract_dist_for
    skip_reason = self._check_skip_installed(req)
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 236, in _check_skip_installed
    req_to_install.check_if_exists(self.use_user_site)
  File "/usr/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 437, in check_if_exists
    if not self.req.specifier.contains(existing_version, prereleases=True):
  File "/usr/lib/python3.9/site-packages/packaging/specifiers.py", line 790, in contains
    item = parse(item)
  File "/usr/lib/python3.9/site-packages/packaging/version.py", line 57, in parse
    return Version(version)
  File "/usr/lib/python3.9/site-packages/packaging/version.py", line 296, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```

The following version of PIP is used:
```
$ pip --version
pip 20.2.1 from /usr/lib/python3.9/site-packages/pip (python 3.9)
```
And the following version of Python:
```
$ python --version
Python 3.9.0
```

**Comment by ITAYC0HEN** [comment]
As a **workaround**, one can edit `/usr/lib/python3.9/site-packages/packaging/version.py` and cast the `version` to `str`

Before:
```
match = self._regex.search(version)
```

After:
```
match = self._regex.search(str(version))
```

**Comment by dschult** [comment]
Just as a warning/disclaimer, Networkx v2.5 doesn't support Python 3.9.  Most everything should work, but it wasn't tested on Python 3.9 before being released.

We expect networkx v2.6 to be released fairly soon and it does/will support Python 3.9. 
In the meantime you can install the github latest branch to get a version tested on 3.9.
