### ISSUE TITLE
Unable to build from source using source archive from PyPI

### ISSUE THREAD

**Issue by nandahkrishna** [networkx/networkx#4959]
When using the source archive for NetworkX 2.6 from PyPI, building from source fails. This seems to be because the `requirements/` folder is not present in the archive, and is a consequence of changes to the `setup.py` file in commit https://github.com/networkx/networkx/commit/cf5cc90b25fb53aec85c59d8d62fae3d3b05bc86 (due to which requirements are populated from files in the `requirements/` directory).

This was not an issue with stable versions prior to 2.6 (such as 2.5.1) even though the `requirements/` directory was not included in the archive, because the requirements were listed directly in `setup.py`.

(**Note:** I wasn't sure if a Discussion would be better than an Issue for this, but decided to go ahead with a bug report because it seems to me like this is a packaging bug. Apologies in advance if this should have been reported elsewhere.)

### Current Behavior

As mentioned above, building NetworkX 2.6 from source using the archive from PyPI fails because of the absence of the `requirements/` directory, which is used to populate dependencies in `setup.py`. This is an problem when a user wishes to build from source, such as when using `pip install --no-binary`.

### Expected Behavior

I would expect the `requirements/` folder to be present in the source archive, so that the build succeeds.

### Steps to Reproduce

```
➜ pip install --no-binary :all: networkx==2.6
Collecting networkx==2.6
  Downloading networkx-2.6.tar.gz (1.8 MB)
     |████████████████████████████████| 1.8 MB 2.2 MB/s
    ERROR: Command errored out with exit status 1:
     command: /Users/nanda/miniconda3/envs/dev/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/10/j4yhfzq10mz95_gmsln3z_hc0000gn/T/pip-install-t8bvrwpe/networkx/setup.py'"'"'; __file__='"'"'/private/var/folders/10/j4yhfzq10mz95_gmsln3z_hc0000gn/T/pip-install-t8bvrwpe/networkx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/10/j4yhfzq10mz95_gmsln3z_hc0000gn/T/pip-pip-egg-info-ndhnqncu
         cwd: /private/var/folders/10/j4yhfzq10mz95_gmsln3z_hc0000gn/T/pip-install-t8bvrwpe/networkx/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/10/j4yhfzq10mz95_gmsln3z_hc0000gn/T/pip-install-t8bvrwpe/networkx/setup.py", line 165, in <module>
        install_requires = parse_requirements_file("requirements/default.txt")
      File "/private/var/folders/10/j4yhfzq10mz95_gmsln3z_hc0000gn/T/pip-install-t8bvrwpe/networkx/setup.py", line 159, in parse_requirements_file
        with open(filename) as fid:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements/default.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

### Environment

Python version: 3.8.0
NetworkX version: 2.6.0

While these is my local environment, the main reason I'm opening this issue is because of a build failure noticed at [Homebrew](https://brew.sh), when building NetworkX 2.6 from source for another dependent package. At Homebrew, packages must be built from source and wheel files or other precompiled binaries cannot be used.

### Additional context

The relevant Homebrew pull request is Homebrew/homebrew-core#80829, and the logs can be viewed [here](https://github.com/Homebrew/homebrew-core/commit/ad5fc3dff1c0a6929b81cb14fb66fda5c29e3e7c/checks/3022390612/logs).

**Comment by nandahkrishna** [comment]
This should be fixed by 2.6.1, I've confirmed that the `requirements/` directory is present in the source archive. Thanks for the quick fix, `@jarrodmillman`.
