### ISSUE TITLE
AttributeError When Loading Node Link Data 

### ISSUE THREAD

**Issue by ibraheemalayan** [networkx/networkx#5627]
I have a graph where its nodes are objects of a serializable class [ City ], the graph is serialized to json using 
```python
json_g = nx.node_link_data(g)
```

then the json is saved in a file, when I try to load the file into a graph
```python
import networkx as nx

data = ""
with open("res.json", "r") as res_file:
    data = res_file.readlines()

g = nx.node_link_graph(data)

nx.draw(g)
```

### Current Behavior

I get the following error
```
Traceback (most recent call last):
  File "/-------------------------------------------code/draw.py", line 8, in <module>
    g = nx.node_link_graph(data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/networkx/readwrite/json_graph/node_link.py", line 166, in node_link_graph
    multigraph = data.get("multigraph", multigraph)
AttributeError: 'list' object has no attribute 'get'
```

### Expected Behavior
It should simply work

### Steps to Reproduce

the graph is initialized like the following:

```python
g = nx.Graph()
```

then the nodes are added like this 

```python
c = City(name=row[0], latitude=float(row[1]), longitude=float(row[2]))
g.add_node(c)
```

and edges are added like this
```python
g.add_edge(src_cities[i], dest_cities[j], driving_cost = drive_element["distance"]["value"], walking_cost=walk_element["distance"]["value"])
```

the City class
```python
class City():
    ''' class representing a node (city) '''
    
    def __init__(self, name: str, latitude: float, longitude: float) -> None:
        
        self.lat = latitude
        self.lng = longitude
        
        self.name = name 
```

the json output looks like
```json
{
    "directed": false,
    "multigraph": false,
    "graph": {},
    "nodes": [
        {
            "id": {
                "lat": 31.7833,
                "lng": 35.2167,
                "name": "Jerusalem"
            }
        },
        {
            "id": {
                "lat": 32.08,
                "lng": 34.78,
                "name": "Yafa"
            }
        },
.
.
.
.
.
        {
            "id": {
                "lat": 31.91001,
                "lng": 35.21645,
                "name": "Al Bira"
            }
        }
    ],
    "links": [
        {
            "driving_cost": 0,
            "walking_cost": 0,
            "source": {
                "lat": 31.7833,
                "lng": 35.2167,
                "name": "Jerusalem"
            },
            "target": {
                "lat": 31.7833,
                "lng": 35.2167,
                "name": "Jerusalem"
            }
        },
.
.
.
.
.
.
        {
            "driving_cost": 0,
            "walking_cost": 0,
            "source": {
                "lat": 31.91001,
                "lng": 35.21645,
                "name": "Al Bira"
            },
            "target": {
                "lat": 31.91001,
                "lng": 35.21645,
                "name": "Al Bira"
            }
        }
    ]
}
```

### Environment
Python version: 3.10.2
NetworkX version: 2.8

**Comment by MridulS** [comment]
`data = res_file.readlines()` this bit of line returns a `list` but `nx.node_link_graph(data)` requires the data to be a dict like object. Use something like `json.load` to read in the data and then pass it to `nx.node_link_graph(data)` :)
