### ISSUE TITLE
treewidth algos depend on node types

### ISSUE THREAD

**Issue by harristeague** [networkx/networkx#5681]
The treewidth functions appear to depend on the types of nodes in the input graph.

### Current Behavior

For example, the algos fail is there is a mix of nodes with integer and string types.

### Expected Behavior

The algos should not depend on node types, only the graph structure.

### Steps to Reproduce

```python
import networkx as nx
from networkx.algorithms.approximation import treewidth
G = nx.Graph()
G.add_nodes_from([0, 'a'])
tw, td = treewidth.treewidth_min_degree(G)
or
tw, td = treewidth.treewidth_min_fill_in(G)
```

### Environment

Python version: 3.8
NetworkX version:  2.8

### Additional context

Error:
  File "<somedir>/lib/python3.8/site-packages/networkx/algorithms/approximation/treewidth.py", line 106, in __init__
    heapify(self._degreeq)
TypeError: '<' not supported between instances of 'int' and 'str'

**Comment by rossbar** [comment]
Thanks for the report @harristeague , I can reproduce this as well.

**Comment by brocla** [comment]
The same error occurs in,
  - `lexicographical_topological_sort` in `algorithms/graphical.py`
  - `MappedQueue` in `algorithms/graphical.py`
  
which also use `heapify`,

> TypeError: '<' not supported between instances of 'int' and 'str'

**Comment by dschult** [comment]
Thanks for those comments @brocla !!

Hmmm...  I thought the `create_tuple` function (line 375) in `dag.py` avoids the issue for `lexicographical_topological_sort`. But that is in `algorithms/dag.py` not `algorithms/graphical.py`. Perhaps I am missing something?

`MappedQueue` is a helper class that let's you put whatever you need to on the queue -- including the responsibility for the developer that is using it to make sure it is sortable.  But again, maybe I am missing the place you are referring to.

Do you have examples that don't work in those functions? Or is this comment based on looking at code?

**Comment by brocla** [comment]
Hello @dschult .  I should have included the examples when I had them the first time. Here is how I triggered the `TypeError`.


```
>>> G = nx.path_graph(5, create_using=nx.DiGraph)
>>> G.add_edge(2, 'a')
>>> G.edges
OutEdgeView([(0, 1), (1, 2), (2, 3), (2, 'a'), (3, 4)])
>>> list(nx.lexicographical_topological_sort(G))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/brocla/python/networkx/networkx/algorithms/dag.py", line 394, in lexicographical_topological_sort
    heapq.heappush(zero_indegree, create_tuple(child))
TypeError: '<' not supported between instances of 'str' and 'int'
```


```
>>> nx.utils.mapped_queue.MappedQueue([916, 50, 'a', 493, 237])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/brocla/python/networkx/networkx/utils/mapped_queue.py", line 132, in __init__
    self._heapify()
  File "/home/brocla/python/networkx/networkx/utils/mapped_queue.py", line 136, in _heapify
    heapq.heapify(self.heap)
TypeError: '<' not supported between instances of 'int' and 'str'
```

BTW, `heapify` is also used in these files, but I was not able to coax them into a `TypeError`.  They seem to be sorting on something besides nodes.
- `algorithms/dag.py`
- `generators/degree_seq.py`

**Comment by dschult** [comment]
Thanks for this! It took me a little while to recall how those two functions handle sorting. We've got it fixed so most of the time it works fine. But your examples show how our unprotected inputs can lead to problems. It would be very helpful to have better documentation; and examples to show how to handle it.

Issues:
- `lexicographical_topological_sort` has an optional second argument `key` which (just like min/max) takes a function that returns the sort value given the node. This is only needed to break ties in the lexicographical ordering. So, if a TypeError is raised due to mixed node types, the user should provide a `key` function that enables comparison of the nodes. For example:
```python
G = nx.path_graph([0, 1, 'a' ,2])
node_order = {node: i  for i, node in enumerate(G)}
nx.lexicographical_topological_sort(G, key=lambda x: node_order[x])
```
We should include an example like this one. There are many other improvements needed in that doc_string. For example, the leading paragraph description (after the one-line description) explains what a topological sort is, but not anything about a lexicographical topological sort. We should also add the TypeError as one of the exceptions that are raised, with a hint to provide a `key` input that returns values that are sortable.

- `MappingQueue` is a priority queue that sorts the items by priority. The priority values are usually provided via a dict keyed by element to the priority of that element. But you can also provide an iterator of elements as input, in which case the elements are also the priorities. To fix the example you show, the user should input a dict holding priorities rather than a list of elements. But that is not clear from the documentation. An example should be included saying that unsortable elements will cause a TypeError and showing an example of how to handle that similar to
```python
inputs = [243, 'a', 213]
node_order = {node: i for i, node in enumerate(inputs)}
M = nx.MappedQueue(node_order)
```
This doc_string does not say much at all. It should at least include a sentence that unsortable elements should have a priority assigned to them upon input via using a dict. Otherwise a TypeError will occur when the comparisons are made. And then include an example of how to make a dict to avoid this problem.

Handling `heapify` library wide:
- Each place we use heapify, we make the elements into tuples which protect the nodes from ever being compared when the tuple-elements that contain the nodes are compared. This is done by putting a unique value in the tuple before the node, e.g. `element = (priority, node_id, node)`. So long as the node_id is unique, comparing tuples will never compare the raw nodes themselves. That is why heapify doesn't lead to a TypeError in those other functions in dag.py and generators.
- In the two cases you exposed, we have provided the flexibility to use the nodes themselves. The freedom comes with responsibility to keep yourself safe. But it is hard to do that without the information about how to do that. So, we need to update the doc_strings.

**Comment by brocla** [comment]
Hi @dschult . Thanks for the clear explanations. It helps me understand the code and the intentions when it was written. Great.

I'd like to draft an update to the docstrings. I'll do them one at a time, `lexicographical_topological_sort` first.

#### Here is what I think I heard...
- Better explanations for the short and long descriptions. Describe lexicographical and topological without using those words.
- Add an explanation of how `key=` solves the un-sortable problem.
- Put a hint in the exception statement that points the user to the `key=` argument.
- Add an example that shows how to solve the un-sortable problem

#### A thought about the example...

Using `enumerate` to generate sortable keys also means that there won't be any lexicographic aspect to the order.
The node positions that are not determined by the topological sort will just be in the order they are stored in the Graph.


What if the example used this key?
```python
>>> sorted([2, 'c', 1, 'b', 3, 'a'], key=lambda node: (isinstance(node, str), node))
[1, 2, 3, 'a', 'b', 'c']
```
It is not general enough solve everyone's sorting problems, but good enough that the example will demonstrate lexi behavior.

**Comment by dschult** [comment]
That list of suggested changes looks good to me.

And I agree that the example you make by putting all strings behind every non-string works for the case of a graph with nodes that are integers or strings. I think that is good enough -- anyone with a more difficult sorting case will have to figure it out.  After all lexicographical implies that the nodes themselves are sortable somehow. :}

**Comment by brocla** [comment]
Hello @dschult 
I started work on adding examples to the doc_string of `MappedQueue`.  I was going to explain how to use dictionaries to assign priorities, but I bumped into two small corner cases and need some direction. Are these worth worrying about?  Or are they too unlikely to deal with?

### #1
When a dictionary is used to assign priorities, if two priorities are the same, _HeapElement tries to resolve the tie by comparing elements. If the elements are incomparable, there is a TypeError:
```python
tie = {243: 1, 'a': 1}
M = nx.MappedQueue(tie)
Traceback (most recent call last):
...
TypeError: '<' not supported between instances of 'str' and 'int'
```
In this case, two rare things have to happen.
(perhaps a fix is to break the second tie by looking at hashes.)


### #2
`_HeapElement` defines `__lt__` and `__gt__`.  When there is a tie in the priority, the `__gt__` method does a '**less than**' check instead of '**greater than**'.  So this happens...
```python
>>> a = nx._HeapElement(1, 'a')
>>> b = nx._HeapElement(1, 'b')
>>> a > b
True
>>> a < b
True
```
I think that the sorting in `heap` only uses `__lt__`, not `__gt__`, so this may have never happened.

Do I worry about these?

**Comment by dschult** [comment]
Wow -- it is definitely a bug that `__gt__` uses a `less than` check to break the ties in `_HeapElement`.  That should be fixed.  

I think there are multiple ways to fix the incomparable problem of the elements in a `_HeapElement`.  Using the hash may not help because hashes are sometimes equal (a dict employs mechanisms to resolve collisions when they are equal).  I think it might be best to raise an exception with a better message. Something like:
```python
        if self.priority == other_priority:
            try:
                   return self.element < other.element
            except TypeError as err:
                   raise TypeError(f"{err}\nConsider using a tuple for the priority to avoid such comparisons: {k: (v, i) for i,(k,v) in enumerate(data.items())}")
        return self.priority < other_priority
```

**Comment by brocla** [comment]
OK. Got it. I think I can fix that up.  Here is my task list...

 - Add Tests
    - test `__gt__` in `_HeapElement` when priorities are tied.
    - test dictionary input in `MappedQueue`
    - test tied priorities
    - verify exception is raised for incomparable elements

 - Fix `__gt__` bug
 - Add the exception for incomparable elements. Include a helpful error message.
 - Add Examples 
     - show that incomparable elements will fail
     - show how to fix incomparable elements by assigning priorities via a dict.

 - Update the doc_string descriptions to explain assigning priorities via a dict.

**Comment by harristeague** [comment]
I'm not sure this a bug, however perhaps a better warning should be
generated.  For lexicographical_topological_sort, the whole idea is to key
the sort off of something comparable with default being the node itself.
If you have nodes that are not comparable, you should provide a different
key.

**Comment by MridulS** [comment]
The last bits were fixed in #5939
