### ISSUE TITLE
graphviz_layout gives the "colon" error on Graph that has no colons anywhere

### ISSUE THREAD

**Issue by rjalexa** [networkx/networkx#6290]
I am plotting the result of Stanford's Stanza NLP pipeline to networkx. The spring_layout works fine but the geometry is not optimal. I therefore tried using the graphviz_layout instead but got the message about not accepting un-escaped ':' unless comprised between two double quotes.
Stanza did generate some strings as 'nsubj:pass" so I wrote a function to replace any colon in any attribute string to nothing, thus changing 'nsubj:pass' to 'nusbjpass'.
Still get the error.
Here is the current code:
```
# position = nx.spring_layout(G)
    print(
        "*" * 30,
        "NODE DATA",
        "*" * 30,
    )
    print(G.nodes(data=True))
    print(
        "*" * 30,
        "EDGE DATA",
        "*" * 30,
    )
    print(G.edges(data=True))
    position = nx.nx_pydot.graphviz_layout(
        G
    ) 
``` 
which show the current Graph data just before invoking the layouting algorithm. Here is the result which seems to show the absence of colons anywhere:
****************************** NODE DATA ******************************
```
[(0, {'id': 0, 'text': 'ROOT', 'lemma': 'ROOT', 'upos': 'ROOT', 'start_char': 0, 'end_char': 0}), (1, {'id': 1, 'text': 'Franco Sigismondi Mochi', 'lemma': 'Franco Sigismondi Mochi-PER', 'upos': 'PER', 'xpos': 'SP', 'head': 6, 'deprel': 'nsubjpass', 'start_char': 1, 'end_char': 24, 'contraction': {3: {'id': 3, 'text': 'Mochi', 'lemma': 'Mochi', 'upos': 'PROPN', 'xpos': 'SP', 'head': 1, 'deprel': 'flatname', 'start_char': 19, 'end_char': 24}, 2: {'id': 2, 'text': 'Sigismondi', 'lemma': 'Sigismondi', 'upos': 'PROPN', 'xpos': 'SP', 'head': 1, 'deprel': 'flatname', 'start_char': 8, 'end_char': 18}}, 'custcol': 'cyan'}), (6, {'id': 6, 'text': 'nominato', 'lemma': 'nominare', 'upos': 'VERB', 'xpos': 'V', 'feats': 'Gender=Masc|Number=Sing|Tense=Past|VerbForm=Part', 'head': 0, 'deprel': 'root', 'start_char': 33, 'end_char': 41}), (7, {'id': 7, 'text': 'presidente', 'lemma': 'presidente', 'upos': 'NOUN', 'xpos': 'S', 'feats': 'Gender=Masc|Number=Sing', 'head': 6, 'deprel': 'xcomp', 'start_char': 42, 'end_char': 52}), (10, {'id': 10, 'text': 'Food and Agriculture Organization', 'lemma': 'Food and Agriculture Organization-ORG', 'upos': 'ORG', 'xpos': 'SP', 'head': 7, 'deprel': 'nmod', 'start_char': 59, 'end_char': 92, 'contraction': {13: {'id': 13, 'text': 'Organization', 'lemma': 'Organization', 'upos': 'PROPN', 'xpos': 'SP', 'head': 12, 'deprel': 'flatname', 'start_char': 80, 'end_char': 92}, 12: {'id': 12, 'text': 'Agriculture', 'lemma': 'Agriculture', 'upos': 'PROPN', 'xpos': 'SP', 'head': 10, 'deprel': 'conj', 'start_char': 68, 'end_char': 79}}, 'custcol': 'palegreen'}), (15, {'id': 15, 'text': 'FAO', 'lemma': 'FAO', 'upos': 'PROPN', 'xpos': 'SP', 'head': 12, 'deprel': 'appos', 'start_char': 94, 'end_char': 97})]
****************************** EDGE DATA ******************************
[(1, 6, {'label': 'nsubjpass'}), (6, 0, {'label': 'root'}), (7, 6, {'label': 'xcomp'}), (10, 7, {'label': 'nmod'}), (15, 10, {'label': 'appos'})]
```
I also tried changing the nx_pydot.py code at line 262-263 to try and have more info from the error message. As follows:
```
if raise_error:
            raise ValueError(f'Node names and attributes should not contain ":" {n}')
```
and now get the following corresponding output:
```
Traceback (most recent call last):
  File "/Users/bob/Documents/work/stanza2graph/stanza2graph.py", line 142, in <module>
    position = nx.nx_pydot.graphviz_layout(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bob/opt/miniconda3/envs/mema/lib/python3.11/site-packages/networkx/drawing/nx_pydot.py", line 353, in graphviz_layout
    return pydot_layout(G=G, prog=prog, root=root)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bob/opt/miniconda3/envs/mema/lib/python3.11/site-packages/networkx/drawing/nx_pydot.py", line 402, in pydot_layout
    P = to_pydot(G)
        ^^^^^^^^^^^
  File "/Users/bob/opt/miniconda3/envs/mema/lib/python3.11/site-packages/networkx/drawing/nx_pydot.py", line 263, in to_pydot
    raise ValueError(f'Node names and attributes should not contain ":" {n}')
ValueError: Node names and attributes should not contain ":" 1

```
### Expected Behavior

I expected to be able to calculate the node positions using graphviz_layout after having taken care of not having any node name or attribute name and content with a colon char.

### Steps to Reproduce
```

"""
Sample program to analyze a phrase with Stanfords STANZA and
build a networkx graph selecting certain token types.
Will display:
    named entities and all of their relations to wanted POS

"""
import stanza
import networkx as nx
import matplotlib.pyplot as plt

IN_TXT = """
Franco Sigismondi Mochi è stato nominato presidente della Food and Agriculture Organization (FAO).
"""
LANG = "it"
ALLOWED_POS = ["NOUN", "PROPN", "VERB"]
NXDOPTS = {
    "edge_color": "powderblue",
    "node_size": 400,
    "width": 2,
}
NOD_COL = "orange"  # color for non NE nodes
PER_COL = "cyan"  # color for PERson Named Entity node
ORG_COL = "palegreen"  # color for ORGanization Named Entity node
OTH_COL = "grey"  # color for other Named Entity node
BOR_COL = "blue"  # color for node border
EDG_COL = "powderblue"  # color for graph edges


def collapse_ne(
    graph: nx.Graph, named_entity: stanza.models.common.doc.Span
) -> nx.Graph:
    """
    Identify all nodes in a named entity span
    Collapse all said nodes substituting them with
    the named entity node info
    add a "lemma" dictionary entry = "text" - "NE type"
    add a "color" property mapped to the NE type
    """
    delendum_nodes = []
    # for every graph node
    for _, wnode in graph.nodes(data=True):  # id of word is both wid and wnode['id']
        # if the word underlies an entity span
        if (wnode["start_char"] >= named_entity.start_char) and (
            wnode["end_char"] <= named_entity.end_char
        ):
            # print(f"{named_entity.text} comprises word {wnode['id']} -> {wnode['text']}") # DEBUG
            delendum_nodes.append(wnode["id"])  # build a list of nodes to collapse
    # now delete all nodes in the list from the graph, conserving the first node
    kept_node = delendum_nodes[0]
    for i in reversed(delendum_nodes):
        if kept_node != i:
            graph = nx.contracted_nodes(
                graph, kept_node, i, self_loops=False
            )  # collapse the word nodes
            # change text, lemma and start/end of start node and add NE type maybe color
            newlabel = named_entity.text + "-" + named_entity.type
            graph.add_node(
                kept_node,
                upos=named_entity.type,
                lemma=newlabel,
            )
            graph.add_node(
                kept_node,
                start_char=named_entity.start_char,
                end_char=named_entity.end_char,
                text=named_entity.text,
            )
            # now color code the named entities
            if named_entity.type == "PER":
                graph.add_node(
                    kept_node,
                    custcol=PER_COL,
                )  # add Named Entity custom color
            elif named_entity.type == "ORG":
                graph.add_node(
                    kept_node,
                    custcol=ORG_COL,
                )  # add Named Entity custom color
            else:
                graph.add_node(
                    kept_node,
                    custcol=OTH_COL,
                )
    return graph


# download appropriate language model
stanza.download(LANG, verbose=False)
nlp = stanza.Pipeline(
    LANG,
    processors="tokenize, pos, lemma, mwt, ner, depparse",
    verbose=False,
    use_gpu=False,
)
# generate a STANZA document from the given text via the pipeline
doc = nlp(IN_TXT)

for sentence in doc.sentences:
    # initialize a G as MultiDiGraph for every sentence
    G = nx.DiGraph()
    # fill the graph with the relevant data adding fictitious ROOT node
    G.add_node(
        0, id=0, text="ROOT", lemma="ROOT", upos="ROOT", start_char=0, end_char=0
    )
    for word in [w for w in sentence.words if w.pos in ALLOWED_POS]:
        wordict = word.to_dict()
        # double quote any value that has a colon to make graphviz layout possible
        for key, value in wordict.items():
            if isinstance(value, str) and ":" in value:
                wordict[key] = value.replace(":", "")
        print(wordict)  # DEBUG
        G.add_node(wordict["id"], **wordict)
        G.add_edge(wordict["id"], wordict["head"], label=wordict["deprel"])
    # for every recognized NE find all words that belong to its span
    for entity in sentence.entities:
        G = collapse_ne(
            G, entity
        )  # collapse words under the NE span in a single new NE node
    # compute graph drawing parameters
    nodelabels = nx.get_node_attributes(G, "lemma")
    edgelabels = nx.get_edge_attributes(G, "label")
    # position = nx.spring_layout(G)
    print(
        "*" * 30,
        "NODE DATA",
        "*" * 30,
    )
    print(G.nodes(data=True))
    print(
        "*" * 30,
        "EDGE DATA",
        "*" * 30,
    )
    print(G.edges(data=True))
    position = nx.nx_pydot.graphviz_layout(
        G
    )  # graphviz would be better but no xxx:yyy attributes
    NXDOPTS = {
        "node_color": [
            data["custcol"] if "custcol" in data else NOD_COL
            for _, data in G.nodes(data=True)
        ],
        "edgecolors": BOR_COL,
        "edge_color": EDG_COL,
        "node_size": 400,
        "width": 2,
    }
    # and now display the graphs
    nx.draw_networkx(G, position, with_labels=True, labels=nodelabels, **NXDOPTS)
    nx.draw_networkx_edge_labels(G, position, edge_labels=edgelabels)
    plt.margins(0.2)
    plt.suptitle(sentence.text, wrap=True)
    plt.show()
    # clear the graph to repeat for another sentence
    G.clear()

```

### Environment
HW&OS: Mac Mini M1 (apple silicon) with MacOS 12.6
Python version: Conda managed environment
python                    3.11.0          h559f36b_0_cpython    conda-forge
NetworkX version:
networkx                  2.8.8              pyhd8ed1ab_0    conda-forge

Dot is installed via homebrew: dot - graphviz version 6.0.2 (0)

**Comment by dschult** [comment]
I think you will have better luck using the `pygraphviz` package than the `pydot` package. Pydot has not been maintained much lately and this colon trouble keeps affecting people. I'm sure there is a way to make that work (other Issues in this github repository have discussed it). But it is likely to be faster to install `pygraphviz` using the conda-forge channel. Then try `nx.nx_pygraphviz.graphviz.layout` instead of nx.nx_pydot.graphviz_layout`.

**Comment by rjalexa** [comment]
@dschult thank you very much. I am a bit confused though. Conda installed pygraphviz as you suggested, then have the following imports ->
```
import networkx as nx
import matplotlib.pyplot as plt
import pygraphviz as pgv
```
then declare and build my networkx Graph:
`G = nx.DiGraph()`
etc etc but when I reach this line:
`position = nx.nx_pygraphviz.graphviz.layout(G)`
it gets the following error:
```
Traceback (most recent call last):
  File "/Users/bob/Documents/work/stanza2graph/stanza2graph.py", line 127, in <module>
    position = nx.nx_pygraphviz.graphviz.layout(G)
               ^^^^^^^^^^^^^^^^
  File "/Users/bob/opt/miniconda3/envs/mema/lib/python3.11/site-packages/networkx/__init__.py", line 51, in __getattr__
    raise AttributeError(f"module {__name__} has no attribute {name}")
AttributeError: module networkx has no attribute nx_pygraphviz
```
feel dumb :(

**Comment by dschult** [comment]
Ack!   Sorry -- feeling dumber... :}
The name of the module is nx_agraph not nx_pygraphviz....  That's what I get for not actually trying the code I suggest.
It also looks like I put a period when it should have been a "_"... 
The [docs for the interface ](https://networkx.org/documentation/stable/reference/drawing.html#module-networkx.drawing.nx_agraph) are probably more reliable than my code, but I think this works... (I have tried it... :)

```python
position = nx.nx_agraph.graphviz_layout(G)
```

**Comment by rjalexa** [comment]
Eh eh thanks a bunch. Now all good even though both pylint and my middle of the road python knowledge get puzzled as now I am using a pygraphviz function even though I am prefixing it with the nx (networkx).
Do you believe it would be better to close this "bug" or it's better to leave it open?

**Comment by MridulS** [comment]
The graph above does have `:`. The `contracted_nodes` function creates a `contraction` attribute which has a dictionary inside of it

``` python
In [14]: G.nodes[10]
Out[14]:
{'id': 10,
 'text': 'Food and Agriculture Organization',
 'lemma': 'Food and Agriculture Organization-ORG',
 'upos': 'ORG',
 'xpos': 'SP',
 'head': 7,
 'deprel': 'nmod',
 'start_char': 59,
 'end_char': 92,
 'contraction': {13: {'id': 13,
   'text': 'Organization',
   'lemma': 'Organization',
   'upos': 'PROPN',
   'xpos': 'SP',
   'head': 12,
   'deprel': 'flatname',
   'start_char': 80,
   'end_char': 92},
  12: {'id': 12,
   'text': 'Agriculture',
   'lemma': 'Agriculture',
   'upos': 'PROPN',
   'xpos': 'SP',
   'head': 10,
   'deprel': 'conj',
   'start_char': 68,
   'end_char': 79}},
 'custcol': 'palegreen'}
```

and when we try to stringify it https://github.com/networkx/networkx/blob/9256ef670730b741105a9264197353004bd6719f/networkx/drawing/nx_pydot.py#L253 it creates a string with the value `{13: {'id': 13, 'text': 'Organization', 'lemma': 'Organization', 'upos': 'PROPN', 'xpos': 'SP', 'head': 12, 'deprel': 'flatname', 'start_char': 80, 'end_char': 92}, 12: {'id': 12, 'text': 'Agriculture', 'lemma': 'Agriculture', 'upos': 'PROPN', 'xpos': 'SP', 'head': 10, 'deprel': 'conj', 'start_char': 68, 'end_char': 79}}` as a string.

I'm not sure what's the right thing to do here. Should we allow users to have a node/edge attributes with no limit on what goes in the attribute dictionary? I am not a 100% sure if there is a direct translation from `{'attribute' : {'internal_dict_of_attribute`: .....}}` to GraphViz.

**Comment by Qudirah** [comment]
@dschult this issue should be closed then?
