### ISSUE TITLE
`negative_edge_cycle` unexpectedly raises for empty graph input

### ISSUE THREAD

**Issue by eriknw** [networkx/networkx#6465]
### Current Behavior

```python-traceback
>>> import networkx as nx
>>> G = nx.Graph()
>>> nx.negative_edge_cycle(G)
Traceback (most recent call last):
  File "/home/erik/graphblas_workspace/networkx/networkx/algorithms/shortest_paths/weighted.py", line 2138, in negative_edge_cycle
    bellman_ford_predecessor_and_distance(
  File "/home/erik/graphblas_workspace/networkx/networkx/classes/backends.py", line 143, in wrapper
    return func(*args, **kwds)
  File "/home/erik/graphblas_workspace/networkx/networkx/algorithms/shortest_paths/weighted.py", line 1221, in bellman_ford_predecessor_and_distance
    raise nx.NodeNotFound(f"Node {source} is not found in the graph")
networkx.exception.NodeNotFound: Node -1 is not found in the graph

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/erik/graphblas_workspace/networkx/networkx/classes/graph.py", line 672, in remove_node
    nbrs = list(adj[n])  # list handles self-loops (allows mutation)
KeyError: -1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/erik/graphblas_workspace/networkx/networkx/classes/backends.py", line 143, in wrapper
    return func(*args, **kwds)
  File "/home/erik/graphblas_workspace/networkx/networkx/algorithms/shortest_paths/weighted.py", line 2144, in negative_edge_cycle
    G.remove_node(newnode)
  File "/home/erik/graphblas_workspace/networkx/networkx/classes/graph.py", line 675, in remove_node
    raise NetworkXError(f"The node {n} is not in the graph.") from err
networkx.exception.NetworkXError: The node -1 is not in the graph.
```

### Expected Behavior
```python
>>> import networkx as nx
>>> G = nx.Graph()
>>> nx.negative_edge_cycle(G)
False
```

### Steps to Reproduce

See above.

### Environment

Python version: 3.10.9
NetworkX version: main branch
```
commit 4a6f2f43508d26d0eb9884a24cba28721d5fb875 (HEAD -> main, origin/main, origin/HEAD)
Author: Ross Barnowski <rossbar@berkeley.edu>
Date:   Thu Mar 2 06:40:41 2023 -0800
```
### Additional context

Dispatching coming soon... 😉

**Comment by PurviChaurasia** [comment]
Hi! I would like to work on this issue as a part of Outreachy 2023. Could you guide me a bit about how I can get started looking into this? I have completed the basic tasks put up by @MridulS on the outreachy repo.

**Comment by dschult** [comment]
I think the fix will be to add a check a check for G being empty (`G.size() == 0`) early in the function. If it is empty then return `False`.  Then you should add a test in the `tests/test_weighted.py` file where it test the `negative_edge_cycle` function.

**Comment by PurviChaurasia** [comment]
Yep, I'll look into it, thanks!

**Comment by PurviChaurasia** [comment]
Hi, I have fixed the error in the code, however I haven't written tests before. Could someone point out any resources which could help me get started?

**Comment by PurviChaurasia** [comment]
Meanwhile should I create a PR for this and create an issue for the test separately?

**Comment by PurviChaurasia** [comment]
@dschult @MridulS some test cases are failing. Could you please help me out and tell what changes can I make? This is the first time I am contributing, extremely sorry for the inconvenience!

**Comment by dschult** [comment]
Fixed in PR #6473
