### ISSUE TITLE
Louvain is non-deterministic given seed

### ISSUE THREAD

**Issue by nagar-omer** [networkx/networkx#6655]
```
nx_comm.louvain_communities(gnx, resolution=resolution, seed=2602)
```
gives different results for two graphs gnx1, gnx2, where the two have the same nodes and edges. 

the bug is happening because the first partitioning does not take into account the order of the nodes. 

::fix::
louvain.py line 166
```
 partition = [{u} for u in sorted(G.nodes())]
```

further more there is a bug in nx.utils.edges_equal(gnx1, gnx2)
`edges_equal` gets for an input two list of ints (maybe nodes) instead lists of edges
```
Traceback (most recent call last):
  File "/Users/omernagar/opt/miniconda3/envs/vl/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3460, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-14-9d7507674740>", line 1, in <module>
    nx.utils.edges_equal(gnx1, gnx2)
  File "/Users/omernagar/opt/miniconda3/envs/vl/lib/python3.8/site-packages/networkx/utils/misc.py", line 652, in edges_equal
    u, v = e[0], e[1]
TypeError: 'int' object is not subscriptable
```

**Comment by dschult** [comment]
Nodes are not always sorted -- for example if you have some nodes that are strings and others that are integer -- or maybe the nodes are networkx graphs.  It's important to keep in mind that two graphs with the same nodes and the same edges but a different order for the nodes will lead to different results. I think that means we need more warnings about that in the doc_strings. But also we might want to consider making it possible to specify to `louvain` which order of nodes to use. 

For `edges_equal` the two inputs need to be collections of edges -- not graphs.  The graphs iterate over nodes and that's what causes the error (with integer nodes, you can't subscript them -- and you shouldn't be able to). So one possible fix is `edges_equal(gnx1.edges, gnx2.edges)` (untested).

**Comment by eriknw** [comment]
Can we close this? Many algorithms are dependent on order of iteration. Louvain is a random algorithm by design--there isn't a single solution that should be returned--and there is a `seed` argument for reproducibility on the same graph.

**Comment by dschult** [comment]
Yes -- let's close this as "wont fix"
