### ISSUE TITLE
Input graph is not chordal for complete_to_chordal_graph

### ISSUE THREAD

**Issue by richardrl** [networkx/networkx#6863]
### Current Behavior
I input an unweighted graph into `complete_to_chordal_graph`, and it returns this error:
```
Traceback (most recent call last):
  File "graph_csp_test.py", line 99, in <module>
    G_chordal = nx.complete_to_chordal_graph(G_csp)
  File "/usr/local/lib/python3.8/dist-packages/networkx/utils/decorators.py", line 766, in func
    return argmap._lazy_compile(__wrapper)(*args, **kwargs)
  File "<class 'networkx.utils.decorators.argmap'> compilation 8", line 4, in argmap_complete_to_chordal_graph_5
  File "/usr/local/lib/python3.8/dist-packages/networkx/algorithms/chordal.py", line 402, in complete_to_chordal_graph
    if nx.is_chordal(H):
  File "/usr/local/lib/python3.8/dist-packages/networkx/utils/decorators.py", line 766, in func
    return argmap._lazy_compile(__wrapper)(*args, **kwargs)
  File "<class 'networkx.utils.decorators.argmap'> compilation 13", line 5, in argmap_is_chordal_9
  File "/usr/local/lib/python3.8/dist-packages/networkx/algorithms/chordal.py", line 83, in is_chordal
    return len(_find_chordality_breaker(G)) == 0
  File "/usr/local/lib/python3.8/dist-packages/networkx/algorithms/chordal.py", line 331, in _find_chordality_breaker
    raise nx.NetworkXError("Input graph is not chordal.")
networkx.exception.NetworkXError: Input graph is not chordal.

```

### Expected Behavior
I would expect it to complete the graph! And not error that the input is not chordal, the whole point is to turn non-chordal inputs to chordal graphs.

### Steps to Reproduce
```
np_arr = np.array([[1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

G_csp = nx.from_numpy_array(np_arr)
G_chordal = nx.complete_to_chordal_graph(G_csp)
```

### Environment
Python version: 3.8
NetworkX version: 3.1

**Comment by MridulS** [comment]
Yeah this one is tricky, as the graph `G_csp` has self loops.

If you try the development version of networkx you should get a new error `NetworkXError: Self loop found in _is_complete_graph()` maybe it's better than `NetworkXError: Input graph is not chordal.`. This new behavior was added in https://github.com/networkx/networkx/pull/6563.

self-loops are not allowed in chordal graphs, and currently we silently ignore them. Should we forcefully remove the self loop edges or ignore them?

With https://github.com/networkx/networkx/pull/6864 `G_csp` would be classified as a chordal graph as it will silently ignore the self loops.

**Comment by richardrl** [comment]
You could ignore the self-loops, they aren't necessary. I am trying to partition the node into a list of maximum cliques that satisfies the running intersection property.
