### ISSUE TITLE
weird problem with importing networkx

### ISSUE THREAD

**Issue by bbrendon** [networkx/networkx#7144]
If I run this script, html3.py, it runs some other script. If I comment out the line `import networkx as nx`, everything is fine.  The running of the script and contents of it are below.

I'm no python expert.

networkx v 3.2.1 (installed with pip, in a venv)

```
❯ python3 /Users/myuser/p/org_chart/html/html3.py
Traceback (most recent call last):
  File "/Users/myuser/p/org_chart/html/html3.py", line 13, in <module>
    import networkx as nx
  File "/Users/myuser/p/org_chart/venv/lib/python3.11/site-packages/networkx/__init__.py", line 38, in <module>
    from networkx import readwrite
  File "/Users/myuser/p/org_chart/venv/lib/python3.11/site-packages/networkx/readwrite/__init__.py", line 14, in <module>
    from networkx.readwrite.gml import *
  File "/Users/myuser/p/org_chart/venv/lib/python3.11/site-packages/networkx/readwrite/gml.py", line 30, in <module>
    import html.entities as htmlentitydefs
  File "/Users/myuser/p/org_chart/html/html.py", line 279, in <module>
    data = ldap()
           ^^^^^^
  File "/Users/myuser/p/org_chart/html/html.py", line 271, in ldap
    users_data = get_ad_users(server_address, username, password, base_dn)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/myuser/p/org_chart/html/html.py", line 217, in get_ad_users
    connection = Connection(server, user=username, password=password, auto_bind=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/myuser/p/org_chart/venv/lib/python3.11/site-packages/ldap3/core/connection.py", line 363, in __init__
    self._do_auto_bind()
  File "/Users/myuser/p/org_chart/venv/lib/python3.11/site-packages/ldap3/core/connection.py", line 387, in _do_auto_bind
    self.open(read_server_info=False)
  File "/Users/myuser/p/org_chart/venv/lib/python3.11/site-packages/ldap3/strategy/sync.py", line 57, in open
    BaseStrategy.open(self, reset_usage, read_server_info)
  File "/Users/myuser/p/org_chart/venv/lib/python3.11/site-packages/ldap3/strategy/base.py", line 154, in open
    raise LDAPSocketOpenError('invalid server address')
ldap3.core.exceptions.LDAPSocketOpenError: invalid server address
❯ cat html/html3.py
r"""
b

This is going to attempt to use networkx instead of the previous attempts.

pip3 install networkx
"""
from graphviz import Digraph

# from ldap3 import Server, Connection, ALL, SUBTREE

# import json
import networkx as nx


def build_org_structure(users_data):
    pass

```

**Comment by bbrendon** [comment]
It seems it problem is because I have files named html? Is this a bug in networkx?

**Comment by dschult** [comment]
You have run into a name collision. There is a [Python builtin library named html](https://docs.python.org/3/library/html.html) that networkx uses.  You have another python module named `html.py` .  Any python program that uses this python feature (the html builtin library) will not run for you. It is a restriction of the python import command. If you want to name your module `collections.py` you won't be able to use both Python's collections module **and** your module.  Python let's you hide other libraries -- which can be seen as a bug or a feature -- seems like a wart to me.  But you should probably rename your file to something more informative. perhaps `orgchart_html.py`?

**Comment by MridulS** [comment]
Closing this as this isn't networkx specific.
