### ISSUE TITLE
Inconsistent behaviour between connectionstyle bar and arc3 - "ValueError: too many values to unpack (expected 3)"

### ISSUE THREAD

**Issue by nils-huegel** [networkx/networkx#7735]
### Current Behavior

I get a "ValueError: too many values to unpack (expected 3)"

### Expected Behavior

Edge label is plotted

### Steps to Reproduce

```python
import matplotlib.pyplot as plt
import networkx as nx


g = nx.DiGraph()
g.add_node(1)
g.add_node(2)
g.add_edge(1, 2)

pos = nx.shell_layout(g)

nx.draw_networkx_nodes(g, pos)
nx.draw_networkx_labels(g, pos)

edge = (1, 2)
style_arc = "arc3,rad=0.0"
style_bar = "bar,fraction=0.1"

# Both work
nx.draw_networkx_edges(g, pos, edgelist=[edge], connectionstyle=style_arc)
nx.draw_networkx_edges(g, pos, edgelist=[edge], connectionstyle=style_bar)

# Works as expected
nx.draw_networkx_edge_labels(g, pos, edge_labels={edge: "edge"}, connectionstyle=style_arc)

# Doesn't work
nx.draw_networkx_edge_labels(g, pos, edge_labels={edge: "edge"}, connectionstyle=style_bar)

plt.show()

```

### Environment

Python version: 3.13
NetworkX version: 3.4.2

### Additional context

```
Traceback (most recent call last):
  File "min.py", line 27, in <module>
    nx.draw_networkx_edge_labels(g, pos, edge_labels={edge: "edge"}, connectionstyle=style_bar)
  File ".venv/lib/python3.12/site-packages/networkx/drawing/nx_pylab.py", line 1557, in draw_networkx_edge_labels
    text_items[edge] = CurvedArrowText(
                       ^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/networkx/drawing/nx_pylab.py", line 1372, in __init__
    self.x, self.y, self.angle = self._update_text_pos_angle(arrow)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/networkx/drawing/nx_pylab.py", line 1410, in _update_text_pos_angle
    (x1, y1), (cx, cy), (x2, y2) = path_disp.vertices
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 3)
```

**Comment by rossbar** [comment]
Thanks for reporting - I confirm I can reproduce this on da5a0103.

Adding `connectionstyle` to the edge label drawing was done in #7010 - @dg-pb any quick thoughts?

**Comment by dg-pb** [comment]
will look into it.

**Comment by dg-pb** [comment]
Ah, at the time I have only made sure it works for `arc` and `angle` connection styles.

However, I think it is simple and useful style to have:
![Figure_1](https://github.com/user-attachments/assets/f4611956-5779-4bcd-ae5c-83f142a4aa79)

Simple and small change as it is always a straight line:
```python
def _update_text_pos_angle(self, arrow):
    # Fractional label position
    # Text position at a proportion t along the line in display coords
    # default is 0.5 so text appears at the halfway point
    t = self.label_pos
    # Horizontal text labels if unchanged later
    angle = 0
    path_disp = self._get_arrow_path_disp(arrow)
    cstyle = arrow.get_connectionstyle()
    if isinstance(cstyle, mpl.patches.ConnectionStyle.Bar):
        # Only 2 corners are needed
        _, (cx1, cy1), (cx2, cy2), _ = path_disp.vertices
        x = (cx1 + cx2) * t
        y = (cy1 + cy2) * t
        if not self.labels_horizontal:
            # Labels parallel to curve
            change_x = (cx2 - cx1) / 2
            change_y = (cy2 - cy1) / 2
            angle = (np.arctan2(change_y, change_x) / (2 * np.pi)) * 360
    else:
        (x1, y1), (cx, cy), (x2, y2) = path_disp.vertices
        tt = 1 - t
        x = tt**2 * x1 + 2 * t * tt * cx + t**2 * x2
        y = tt**2 * y1 + 2 * t * tt * cy + t**2 * y2
        if not self.labels_horizontal:
            # Labels parallel to curve
            change_x = 2 * tt * (cx - x1) + 2 * t * (x2 - cx)
            change_y = 2 * tt * (cy - y1) + 2 * t * (y2 - cy)
            angle = (np.arctan2(change_y, change_x) / (2 * np.pi)) * 360
    # Text is "right way up"
    if angle > 90:
        angle -= 180
    if angle < -90:
        angle += 180
    (x, y) = self.ax.transData.inverted().transform((x, y))
    return x, y, angle
```

**Comment by nilsh** [comment]
Yep, looks great, thanks!

**Comment by nils-huegel** [comment]
Yep, looks great, thanks!
